/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package ca.robokids.robooffice.gui.test;

import ca.robokids.robooffice.desktop.tabs.students.components.ClassRecordsPanel;
import ca.robokids.robooffice.entity.schoolmetadata.CourseSection;
import ca.robokids.robooffice.entity.schoolmetadata.DayOfWeek;
import ca.robokids.robooffice.entity.schoolmetadata.Project;
import ca.robokids.robooffice.entity.schoolmetadata.Timeslot;
import ca.robokids.robooffice.entity.student.ClassRecord;
import ca.robokids.robooffice.logic.student.StudentManager;
import java.sql.Date;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.UIManager;

/**
 *
 * @author Coldsoft
 */
public class ClassRecordsPanelDriver extends javax.swing.JFrame {

    /** Creates new form ClassRecordsPanelDriver */
    public ClassRecordsPanelDriver() {
        initComponents();
        panel.setClassRecords(getList(),8);
    }

    private List<ClassRecord> getList()
    {
       List<ClassRecord> list = new ArrayList();
       for (int i=1; i<=6; i++)
       {
          list.add(getSampleClassRecord());
       }
       return list;
    }
    private ClassRecord getSampleClassRecord() {
       Random random = new Random();
      ClassRecord cr = new ClassRecord();
      cr.setAttendDate(new Date(System.currentTimeMillis()));
      Timeslot time = new Timeslot();
      time.setDayOfWeek(DayOfWeek.Wed);
      time.setStart((new Time(System.currentTimeMillis())));
      CourseSection section = new CourseSection();
      section.setTimeslot(time);
      cr.setSection(section);
      cr.setComplete(random.nextBoolean());
      if (cr.isComplete()){
      Project p = new Project();
      p.setName(StudentManager.getRandomFirstName()+StudentManager.getRandomLastName());
      cr.setProject(p);
      }
      cr.setTest(random.nextBoolean());
      cr.setMakeupClass(random.nextBoolean());
      cr.setOverdue(random.nextBoolean());
      return cr;
   }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new ca.robokids.robooffice.desktop.tabs.students.components.ClassRecordsPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 150));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(panel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           UIManager.put("DropDownButton.arrowIconGap", 0);
            javax.swing.UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassRecordsPanelDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassRecordsPanelDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassRecordsPanelDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassRecordsPanelDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassRecordsPanelDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ca.robokids.robooffice.desktop.tabs.students.components.ClassRecordsPanel panel;
    // End of variables declaration//GEN-END:variables

}
