/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package ca.robokids.robooffice.gui.test;

import ca.robokids.robooffice.desktop.tabs.school.components.TimeslotDialog;
import ca.robokids.robooffice.desktop.loaders.FramePropertyLoader;
import ca.robokids.robooffice.entity.schoolmetadata.Timeslot;
import de.javasoft.swing.JYSearchField;
import de.javasoft.swing.plaf.jysearchfield.SearchActionEvent;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.Action;
import javax.swing.UIManager;

/**
 *
 * @author Coldsoft
 */
public class TestJFrame extends javax.swing.JFrame implements Action{
JYSearchField field = new JYSearchField();
    /** Creates new form TestJFrame */
    public TestJFrame() {
        initComponents();
         btnRemove.setOpaque(true);
        lblMsg.setText("<html><center>1st line<br>2nd linesssssssss<br>3rd line</center></html>");
        field.setMaximumSize(new Dimension(200,25));
        field.setPromptText("Search Student");
        field.setSearchControlsPosition(JYSearchField.SearchControlsPosition.CLEAR_LEADING_SEARCH_TRAILING);
        field.setSearchMode(JYSearchField.SearchMode.AUTO);
        field.setSearchAction(this);
        field.setSearchDelay(200);
        
        searchPanel.add(field);
        
        //tabPane.setCloseButtonStrategy(JYTabbedPane.CloseButtonStrategy.ALL_TABS);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRemove = new javax.swing.JButton();
        txtTabname = new javax.swing.JTextField();
        lblMsg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRemove.setBackground(new java.awt.Color(255, 51, 102));
        btnRemove.setText("<html><center>1st line<br>2nd linesssssssss<br>3rd line</center></html>");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        lblMsg.setFont(new Font("宋体", Font.PLAIN, 12));
        lblMsg.setText(FramePropertyLoader.getLoadingMessage());

        jButton1.setText("Timeslots");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        searchPanel.setLayout(new javax.swing.BoxLayout(searchPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(txtTabname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTabname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(lblMsg)
                .addGap(55, 55, 55)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      TimeslotDialog time = new TimeslotDialog(this,true);
      time.setLocationRelativeTo(this);
      time.setVisible(true);
      
      Timeslot t = time.getTimeslot();
      System.out.println(t);
      if (t != null){
         lblMsg.setText(t.toString());
         System.out.println(t);
      }
      
   }//GEN-LAST:event_jButton1ActionPerformed

   private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.put("Synthetica.rootPane.titlePane.title.center", Boolean.TRUE);
            UIManager.put("Synthetica.tabbedPane.tab.selected.bold", Boolean.TRUE);
            UIManager.put("Synthetica.rootPane.titlePane.dropShadow", Boolean.TRUE);
            UIManager.put("Synthetica.rootPane.titlePane.gap", 5);
            javax.swing.UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField txtTabname;
    // End of variables declaration//GEN-END:variables

   @Override
   public Object getValue(String key) {
      return null;
   }

   @Override
   public void putValue(String key, Object value) {
      
   }

   @Override
   public void actionPerformed(ActionEvent e) {
      SearchActionEvent s = (SearchActionEvent)e;
      
         System.out.println(field.getText());
   }

}
