/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.robokids.robooffice.desktop.tabs.user;

import ca.robokids.robooffice.desktop.customSwing.UserInfoPanel;
import ca.robokids.robooffice.desktop.main.MainRoboOfficeJFrame;
import ca.robokids.robooffice.desktop.tabs.Tab;
import ca.robokids.robooffice.logic.usermanagement.UserActivity;

/**
 *
 * @author Coldsoft
 */
public class UserAccountTab extends javax.swing.JPanel implements Tab{

   /**
    * Creates new form UserAccountTab
    */
   UserInfoPanel userPane;
   public UserAccountTab() {
      initComponents();

      initialize();
      
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

   @Override
   public void initialize() {
      java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();;
      gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        
      userPane = new UserInfoPanel(this);
      add(userPane,gridBagConstraints);      
      refresh();
   }

   @Override
   public void refresh() {
      if (userPane.getUser() == null)
      {
         userPane.setUser(UserActivity.loginUser);
      }
      
   }

   @Override
   public void setFocus() {
      this.userPane.requestFocus();
   }
}
