/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.robokids.robooffice.desktop.customSwing;

import ca.robokids.exception.BadFieldException;
import ca.robokids.exception.DatabaseException;
import ca.robokids.robooffice.desktop.loaders.FontsLoader;
import ca.robokids.robooffice.desktop.tabs.Tab;
import ca.robokids.robooffice.desktop.util.PopupMessage;
import ca.robokids.robooffice.entity.schoolmetadata.Activity;
import ca.robokids.robooffice.entity.schoolmetadata.Classroom;
import ca.robokids.robooffice.logic.schoolsettings.SchoolManager;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Coldsoft
 */
public class ClassroomInfoPanel extends javax.swing.JPanel {

   /**
    * Creates new form ClassroomInfoPanel
    */
   DefaultListModel<Activity> activityModel = new DefaultListModel();
   Classroom classroom;
   Tab parent;
   public ClassroomInfoPanel(Tab parent) {
      initComponents();
      this.parent = parent;
      
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCapacity = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstActivity = new javax.swing.JList();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblMsgDisplay = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstActivity1 = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblErrorMsgEdit = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        spinCapacity = new com.toedter.components.JSpinField();

        setLayout(new java.awt.CardLayout());

        lblName.setFont(FontsLoader.getBigStaticLabelFont());
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(FontsLoader.getStaticLabelFont());
        jLabel1.setText("Capacity:");

        lblCapacity.setFont(FontsLoader.getDynamicLabelFont());

        jLabel2.setFont(FontsLoader.getStaticLabelFont());
        jLabel2.setText("Location:");

        lblLocation.setFont(FontsLoader.getDynamicLabelFont());

        jLabel3.setFont(FontsLoader.getStaticLabelFont());
        jLabel3.setText("Current Course and Memberships");

        lstActivity.setFont(FontsLoader.getBigListFont());
        lstActivity.setModel(activityModel);
        jScrollPane1.setViewportView(lstActivity);

        btnEdit.setFont(FontsLoader.getButtonFont());
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(FontsLoader.getButtonFont());
        btnDelete.setForeground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblMsgDisplay.setFont(FontsLoader.getErrorLabelFont());

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(displayLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(displayLayout.createSequentialGroup()
                        .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblMsgDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(displayLayout.createSequentialGroup()
                                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(displayLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)
                                    .addComponent(btnEdit))
                                .addGap(132, 132, 132)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)))
                .addContainerGap())
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(display, "display");

        jLabel4.setFont(FontsLoader.getStaticLabelFont());
        jLabel4.setText("Capacity:");

        jLabel6.setFont(FontsLoader.getStaticLabelFont());
        jLabel6.setText("Course and Memberships");

        lstActivity1.setFont(FontsLoader.getBigListFont());
        lstActivity1.setModel(activityModel);
        jScrollPane2.setViewportView(lstActivity1);

        jLabel7.setFont(FontsLoader.getStaticLabelFont());
        jLabel7.setText("Classroom Name:");

        btnSave.setFont(FontsLoader.getButtonFont());
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(FontsLoader.getButtonFont());
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblErrorMsgEdit.setFont(FontsLoader.getErrorLabelFont());

        txtName.setFont(FontsLoader.getTextFieldFont());

        spinCapacity.setFont(FontsLoader.getComboBoxFont());
        spinCapacity.setMaximum(50);
        spinCapacity.setMinimum(0);

        javax.swing.GroupLayout editLayout = new javax.swing.GroupLayout(edit);
        edit.setLayout(editLayout);
        editLayout.setHorizontalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(editLayout.createSequentialGroup()
                        .addComponent(lblErrorMsgEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editLayout.createSequentialGroup()
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addGroup(editLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addGroup(editLayout.createSequentialGroup()
                                .addComponent(spinCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)))
                .addGap(16, 16, 16))
        );
        editLayout.setVerticalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(spinCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMsgEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        add(edit, "edit");
    }// </editor-fold>//GEN-END:initComponents

   private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      if (PopupMessage.createDelete(classroom.toString()))
      {
         try {
            List<Activity> list = SchoolManager.deleteClassroom(classroom);
            if (list != null && PopupMessage.createConfirmPopUp("This classroom contains courses/memberships, it is recommended that you delete those first."
                  + "\n Do you want to force delete? related courses/memberships will be deleted too.","Warning"))
            {

                  SchoolManager.forceDeleteClassroom(classroom);
               
            }
            
         } catch (DatabaseException ex) {
            errorMsgDisplay(ex.getMessage());
         }
      }
      parent.refresh();
   }//GEN-LAST:event_btnDeleteActionPerformed

   private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      CardLayout c = (CardLayout)this.getLayout();
      c.show(this, "display");
      populateFields();
     
   }//GEN-LAST:event_btnCancelActionPerformed

   private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      this.btnSave.setEnabled(false);
      Classroom temp = getFields();
      if (temp != null)
      {
         temp.setClassroom_id(classroom.getClassroom_id());
         temp.setLocation(classroom.getLocation());
         temp.setDeleted(classroom.isDeleted());
         try {
            SchoolManager.modifyClassroom(temp);
            
         } catch (BadFieldException ex) {
            errorMsgEdit(ex.getMessage());
            this.btnSave.setEnabled(true);
            return;
         } catch (DatabaseException ex) {
            PopupMessage.createErrorPopUp(ex.getMessage(), null);
            this.btnSave.setEnabled(true);
            return;
         }
         msgDisplay(classroom + " Saved.");
         classroom = temp;
         CardLayout c = (CardLayout)this.getLayout();
         c.show(this, "display");
         
         this.parent.refresh();
         
      }
      populateFields();
      this.btnSave.setEnabled(true);
      
   }//GEN-LAST:event_btnSaveActionPerformed

   private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
      CardLayout c = (CardLayout)this.getLayout();
         c.show(this, "edit");
   }//GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel display;
    private javax.swing.JPanel edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCapacity;
    private javax.swing.JLabel lblErrorMsgEdit;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMsgDisplay;
    private javax.swing.JLabel lblName;
    private javax.swing.JList lstActivity;
    private javax.swing.JList lstActivity1;
    private com.toedter.components.JSpinField spinCapacity;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

   private void setActivityModel() {
      activityModel.clear();
      try {
         List<Activity> list = SchoolManager.getAllActivityByClassroom(classroom);
         for (Activity a: list)
         {
            activityModel.addElement(a);
         }
      } catch (DatabaseException ex) {
         errorMsgDisplay(ex.getMessage());
      }
      
      
   }

   private void errorMsgDisplay(String message) {
      lblMsgDisplay.setForeground(new Color(255,102,102));
      lblMsgDisplay.setText(message);
   }
   private void errorMsgEdit(String message)
   {
      lblErrorMsgEdit.setForeground(new Color(255,102,102));
      lblErrorMsgEdit.setText(message);
   }

   public void setClassroom(Classroom classroom) {
      if (classroom == null)
      {
         btnEdit.setEnabled(false);
         btnDelete.setEnabled(false);
         lblName.setText("No Classroom in system");
         lblCapacity.setText("");
         lblLocation.setText("");
      }else
      {
      this.classroom = classroom;
      btnEdit.setEnabled(true);
      btnDelete.setEnabled(true);
      setActivityModel();
      populateFields();
      CardLayout c = (CardLayout)this.getLayout();
         c.show(this, "display");
      }
      lblMsgDisplay.setText("");
      lblErrorMsgEdit.setText("");
   }
   public Classroom getClassroom()
   {
      return classroom;
   }

   private void populateFields() {
      lblName.setText(classroom.getName());
      lblCapacity.setText(String.valueOf(classroom.getCapacity()));
      lblLocation.setText(classroom.getLocation().toString());
      txtName.setText(classroom.getName());
      spinCapacity.setValue(classroom.getCapacity());
      
   }

   private Classroom getFields() {
      Classroom cr = new Classroom();
      if (txtName.getText().trim().equals(""))
      {
         errorMsgEdit("Name needs to be filled");
         return null;
         
      }
      if ((Integer)spinCapacity.getValue() < 3)
      {
         if (!PopupMessage.createConfirmPopUp("You entered a very small capacity number.\n Are you sure?", "Hmm..."))
         {
            return null;
         }
      }
      
         
      cr.setName(txtName.getText().trim());
      cr.setCapacity((Integer)spinCapacity.getValue());
      return cr;
   }

   private void msgDisplay(String message) {
      lblMsgDisplay.setForeground(new Color(0,204,51));
      lblMsgDisplay.setText(message);
   }
}
