/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.robokids.robooffice.desktop.customSwing;

import ca.robokids.exception.BadFieldException;
import ca.robokids.exception.DatabaseException;
import ca.robokids.exception.DuplicateNameException;
import ca.robokids.robooffice.desktop.loaders.FontsLoader;
import ca.robokids.robooffice.desktop.main.MainRoboOfficeJFrame;
import ca.robokids.robooffice.desktop.main.TabManager;
import ca.robokids.robooffice.desktop.tabs.school.MembershipTab;
import ca.robokids.robooffice.desktop.util.PopupMessage;
import ca.robokids.robooffice.entity.schoolmetadata.Classroom;
import ca.robokids.robooffice.entity.schoolmetadata.Membership;
import ca.robokids.robooffice.entity.schoolmetadata.ProgressReportType;
import ca.robokids.robooffice.entity.schoolmetadata.Timeslot;
import ca.robokids.robooffice.logic.schoolsettings.SchoolManager;
import java.awt.CardLayout;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Coldsoft
 */
public class MembershipInfoPanel extends javax.swing.JPanel {

   /**
    * Creates new form MembershipInfoPanel
    */
   DefaultListModel<Timeslot> slots = new DefaultListModel();
   DefaultComboBoxModel<Classroom> classroomModel = new DefaultComboBoxModel();
   MembershipTab parent;
   Membership membership;
   boolean editable;
   TimeslotDialog selectTime;

   public MembershipInfoPanel(MembershipTab parent) {
      initComponents();
      selectTime = new TimeslotDialog(MainRoboOfficeJFrame.getInstance(), true);
      loadPanel();
      this.parent = parent;
      btnEdit.setEnabled(false);
      btnDelete.setEnabled(false);
      btnAdd.setEnabled(false);
      btnDeleteTime.setEnabled(false);
      txtCode.setLimit(4);
   }

   public void setMembership(Membership c) {
      membership = c;
      if (c == null) {
         btnEdit.setEnabled(false);
         btnDelete.setEnabled(false);
         btnAdd.setEnabled(false);
         btnDeleteTime.setEnabled(false);
      } else {
         populateFields();
         btnEdit.setEnabled(true);
         btnDelete.setEnabled(true);
         btnAdd.setEnabled(true);
         btnDeleteTime.setEnabled(true);
      }
   }

   public Membership getMembership() {
      if (!editable) {
         return membership;
      } else {
         Membership newMembership = null;
         try {
            newMembership = getFields();
         } catch (BadFieldException ex) {
            lblMsg.setText(ex.getMessage());
            return null;
         }
         newMembership.setId(membership.getId());
         return newMembership;
      }
   }

   public void setEditable(boolean edit) {
      editable = edit;
      if (edit) {
         switchTo("edit");
      } else {
         switchTo("display");
      }
   }

   public void add() {
      membership = null;
      this.reset();
      this.btnAdd.setEnabled(true);
      this.btnDeleteTime.setEnabled(true);
      switchTo("edit");
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postalCodeJTextField1 = new ca.robokids.robooffice.desktop.customSwing.PostalCodeJTextField();
        information = new javax.swing.JPanel();
        display = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        lblRate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblDescription = new javax.swing.JTextArea();
        lblClassroom = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblCode1 = new javax.swing.JLabel();
        cboClassrooms = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        txtRate = new ca.robokids.robooffice.desktop.customSwing.CurrencyJTextField();
        txtDuration = new ca.robokids.robooffice.desktop.customSwing.IntegerNumberJTextField();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        txtCode = new ca.robokids.robooffice.desktop.customSwing.PostalCodeJTextField();
        calStartDate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        calEndDate = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstTimeslots = new javax.swing.JList();
        btnAdd = new javax.swing.JButton();
        btnDeleteTime = new javax.swing.JButton();

        postalCodeJTextField1.setText("postalCodeJTextField1");

        information.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(FontsLoader.getStaticLabelFont());
        jLabel1.setText("Duration(min):");

        jLabel5.setFont(FontsLoader.getStaticLabelFont());
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Start Date:");

        lblDuration.setFont(FontsLoader.getDynamicLabelFont());
        lblDuration.setText("N/A");

        jLabel3.setFont(FontsLoader.getStaticLabelFont());
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Classroom:");

        lblName.setFont(FontsLoader.getBigStaticLabelFont());
        lblName.setText("Membership Name");

        lblCode.setFont(FontsLoader.getBigStaticLabelFont());
        lblCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCode.setText("Membership Code");

        lblRate.setFont(FontsLoader.getDynamicLabelFont());
        lblRate.setText("N/A");

        jLabel2.setFont(FontsLoader.getStaticLabelFont());
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Rate:");

        jLabel7.setFont(FontsLoader.getStaticLabelFont());
        jLabel7.setText("Description:");

        lblDescription.setColumns(20);
        lblDescription.setEditable(false);
        lblDescription.setFont(FontsLoader.getTextFieldFont());
        lblDescription.setLineWrap(true);
        lblDescription.setRows(5);
        lblDescription.setEnabled(false);
        jScrollPane2.setViewportView(lblDescription);

        lblClassroom.setFont(FontsLoader.getDynamicLabelFont());
        lblClassroom.setText("N/A");

        lblStartDate.setFont(FontsLoader.getDynamicLabelFont());
        lblStartDate.setText("N/A");

        btnEdit.setFont(FontsLoader.getButtonFont());
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(FontsLoader.getButtonFont());
        btnDelete.setForeground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel6.setFont(FontsLoader.getStaticLabelFont());
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("End Date:");

        lblEndDate.setFont(FontsLoader.getDynamicLabelFont());
        lblEndDate.setText("N/A");

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayLayout.createSequentialGroup()
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, displayLayout.createSequentialGroup()
                        .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, displayLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, displayLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(displayLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, displayLayout.createSequentialGroup()
                                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                                    .addComponent(lblStartDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblClassroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(displayLayout.createSequentialGroup()
                                        .addComponent(lblDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(lblEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblDuration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRate)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblClassroom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblEndDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );

        information.add(display, "display");

        jLabel8.setFont(FontsLoader.getStaticLabelFont());
        jLabel8.setText(" Duration(min)");

        jLabel9.setFont(FontsLoader.getStaticLabelFont());
        jLabel9.setText("Start Date");

        jLabel10.setFont(FontsLoader.getStaticLabelFont());
        jLabel10.setText("Classroom");

        lblName1.setFont(FontsLoader.getStaticLabelFont());
        lblName1.setText("Membership Name");

        lblCode1.setFont(FontsLoader.getStaticLabelFont());
        lblCode1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCode1.setText("Membership Code");

        cboClassrooms.setFont(FontsLoader.getComboBoxFont());
        cboClassrooms.setModel(this.classroomModel);

        jLabel12.setFont(FontsLoader.getStaticLabelFont());
        jLabel12.setText("Rate $");

        jLabel13.setFont(FontsLoader.getStaticLabelFont());
        jLabel13.setText("Description (Note: description will show up on student payment receipt)");

        txtDescription.setColumns(20);
        txtDescription.setFont(FontsLoader.getTextFieldFont());
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        jScrollPane3.setViewportView(txtDescription);

        txtRate.setFont(FontsLoader.getTextFieldFont());

        txtDuration.setFont(FontsLoader.getTextFieldFont());

        txtName.setFont(FontsLoader.getTextFieldFont());

        btnSave.setFont(FontsLoader.getButtonFont());
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(FontsLoader.getButtonFont());
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblMsg.setFont(FontsLoader.getErrorLabelFont());
        lblMsg.setForeground(new java.awt.Color(255, 0, 0));

        txtCode.setColumns(4);
        txtCode.setFont(FontsLoader.getTextFieldFont());

        calStartDate.setFont(FontsLoader.getTextFieldFont());

        jLabel11.setFont(FontsLoader.getStaticLabelFont());
        jLabel11.setText("End Date");

        calEndDate.setFont(FontsLoader.getTextFieldFont());

        jLabel15.setText("/ month (28 days)");

        javax.swing.GroupLayout editLayout = new javax.swing.GroupLayout(edit);
        edit.setLayout(editLayout);
        editLayout.setHorizontalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editLayout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(editLayout.createSequentialGroup()
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(lblName1)
                                    .addComponent(lblCode1)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboClassrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(editLayout.createSequentialGroup()
                                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtDuration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtRate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13)))
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        editLayout.setVerticalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCode1)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboClassrooms)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        information.add(edit, "edit");

        jLabel14.setFont(FontsLoader.getStaticLabelFont());
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("<html>Weekly<br>Club open<br>time");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lstTimeslots.setFont(FontsLoader.getBigListFont());
        lstTimeslots.setModel(this.slots);
        jScrollPane4.setViewportView(lstTimeslots);

        btnAdd.setFont(FontsLoader.getButtonFont());
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDeleteTime.setFont(FontsLoader.getButtonFont());
        btnDeleteTime.setForeground(new java.awt.Color(255, 0, 0));
        btnDeleteTime.setText("Delete");
        btnDeleteTime.setName("membershipSettings");
        btnDeleteTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteTime))
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(information, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

   private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

      Membership newMembership = null;
      try {
         newMembership = getFields();
      } catch (BadFieldException ex) {
         lblMsg.setText(ex.getMessage());
         return;
      }
      //if save new Membership
      if (membership == null) {
         try {
            membership = SchoolManager.createMembership(newMembership);
            for (Timeslot t : newMembership.getTimeslots()) {
               try {
                  SchoolManager.addMembershipSection(membership, t.getDayOfWeek(), t.getStart());
               } catch (DuplicateNameException ex) {
                  Logger.getLogger(CourseInfoPanel.class.getName()).log(Level.SEVERE, null, ex);
               }
            }
            parent.refresh();
         } catch (DatabaseException ex) {
            PopupMessage.createErrorPopUp(ex.getMessage(), null);
         } catch (BadFieldException ex) {
            lblMsg.setText(ex.getMessage());
         }
      } else {

         newMembership.setId(membership.getId());
         try {
            SchoolManager.modifyMembership(newMembership);
            parent.refresh();
         } catch (DatabaseException ex) {
            PopupMessage.createErrorPopUp(ex.getMessage(), null);
         }
      }

   }//GEN-LAST:event_btnSaveActionPerformed

   private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
      setEditable(true);
   }//GEN-LAST:event_btnEditActionPerformed

   private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      if (PopupMessage.createDelete(membership.toString())) {
         try {
            if (SchoolManager.deleteMembership(membership)) {
               PopupMessage.createInfo(membership + " is deleted.", "Complete");
               this.reset();
               parent.refresh();
            } else {
               PopupMessage.createInfo("Cannot Delete.Membership is already deleted.", null);
            }
         } catch (DatabaseException ex) {
            PopupMessage.createErrorPopUp(ex.getMessage(), "Database Error");
         }
      }

   }//GEN-LAST:event_btnDeleteActionPerformed

   private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      try {
         selectTime.setVisible(true);
         selectTime.setLocationRelativeTo(MainRoboOfficeJFrame.getInstance());

         Timeslot newTime = selectTime.getTimeslot();
         if (newTime == null) {
            return;
         }

         //check for duplication in list
         for (int i = 0; i < slots.getSize(); i++) {
            if (newTime.equals(slots.get(i))) {
               PopupMessage.createErrorPopUp("There already exists a time: " + newTime, "Sorry");
               return;
            }
         }
         this.slots.addElement(newTime);
         if (membership == null) // if the current mode is adding
         {
            return;
         }
         SchoolManager.addMembershipSection(membership, newTime.getDayOfWeek(), newTime.getStart());
         this.slots.addElement(newTime);
      } catch (DuplicateNameException ex) {
         PopupMessage.createErrorPopUp("The new timeslot already existed.", "Sorry");
      } catch (DatabaseException ex) {
         PopupMessage.createErrorPopUp(ex.getMessage(), null);
      }

   }//GEN-LAST:event_btnAddActionPerformed

   private void btnDeleteTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTimeActionPerformed
      int index = lstTimeslots.getSelectedIndex();
      if (index > -1) {
         if (slots.getSize() == 1) {
            PopupMessage.createErrorPopUp("Membership must have at least 1 timeslot assigned to.\nTry adding a new timeslot, then delete this one.", "Cannot delete");
            return;
         }
         try {
            if (membership == null) {
               slots.remove(index);
               return;
            }
            Timeslot delete = slots.elementAt(index);
            SchoolManager.deleteMembershipSection(membership, delete);
            membership.getTimeslots().remove(delete);
            slots.remove(index);

         } catch (DatabaseException ex) {
            PopupMessage.createErrorPopUp(ex.getMessage(), null);
         }
      }
   }//GEN-LAST:event_btnDeleteTimeActionPerformed

   private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      switchTo("display");
      parent.refresh();
   }//GEN-LAST:event_btnCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteTime;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser calEndDate;
    private com.toedter.calendar.JDateChooser calStartDate;
    private javax.swing.JComboBox cboClassrooms;
    private javax.swing.JPanel display;
    private javax.swing.JPanel edit;
    private javax.swing.JPanel information;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblClassroom;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblCode1;
    private javax.swing.JTextArea lblDescription;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblRate;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JList lstTimeslots;
    private ca.robokids.robooffice.desktop.customSwing.PostalCodeJTextField postalCodeJTextField1;
    private ca.robokids.robooffice.desktop.customSwing.PostalCodeJTextField txtCode;
    private javax.swing.JTextArea txtDescription;
    private ca.robokids.robooffice.desktop.customSwing.IntegerNumberJTextField txtDuration;
    private javax.swing.JTextField txtName;
    private ca.robokids.robooffice.desktop.customSwing.CurrencyJTextField txtRate;
    // End of variables declaration//GEN-END:variables

   private void populateFields() {

      this.lblCode.setText(membership.getCode());
      this.lblName.setText(membership.getName());
      this.lblRate.setText(membership.getRateString());
      this.lblDuration.setText(String.valueOf(membership.getDuration()));


      this.lblDescription.setText(membership.getDescription());
      this.lblClassroom.setText(membership.getClassroom().toString());

      this.txtCode.setText(membership.getCode());
      this.txtName.setText(membership.getName());
      this.txtRate.setText(String.valueOf(membership.getRate()));
      this.txtDuration.setText(String.valueOf(membership.getDuration()));
      this.txtDescription.setText(membership.getDescription());
      //set Selection of classroom
      for (int i = 0; i < classroomModel.getSize(); i++) {
         if (membership.getClassroom().getClassroom_id() == classroomModel.getElementAt(i).getClassroom_id()) {
            cboClassrooms.setSelectedIndex(i);
            break;
         }
      }


      this.lblStartDate.setText(membership.getStartDateString());
      this.lblEndDate.setText(membership.getEndDateString());
      this.calStartDate.setDate(membership.getStartDate());
      this.calEndDate.setDate(membership.getEndDate());
      slots.removeAllElements();
      for (Timeslot t : membership.getTimeslots()) {
         slots.addElement(t);
      }


   }

   private void loadPanel() {
      try {
         classroomModel.removeAllElements();

         List<Classroom> classrooms = SchoolManager.loadAllClassroom();
         List<ProgressReportType> reportTypes = SchoolManager.loadAllProgressReportType();

         for (Classroom cr : classrooms) {
            classroomModel.addElement(cr);
         }
         if (classroomModel.getSize() < 1) {
            PopupMessage.createErrorPopUp("There is no classroom setting in the system.\nYou need to go and create a classroom first.", "Warning!");
            TabManager.createTab("classroomSettings");
            TabManager.closeTab(parent.getName());
         }
         cboClassrooms.setSelectedIndex(0);



      } catch (DatabaseException ex) {
         PopupMessage.createErrorPopUp(ex.getMessage(), null);
      }


   }

   private void switchTo(String display) {
      CardLayout c = (CardLayout) information.getLayout();
      c.show(information, display);
   }

   private Membership getFields() throws BadFieldException {
      Membership c = new Membership();
      c.setCode(txtCode.getText().trim());
      c.setName(txtName.getText().trim());
      c.setDescription(txtDescription.getText().trim());
      if (txtDuration.getText().trim().length() == 0) {
         c.setDuration(0);
      } else {
         c.setDuration(Integer.valueOf(txtDuration.getText().trim()));
      }
      if (txtRate.getText().trim().length() == 0) {
         c.setRate(0f);
      } else {
         c.setRate(Float.valueOf(txtRate.getText().trim()));
      }
      c.setClassroom(classroomModel.getElementAt(cboClassrooms.getSelectedIndex()));
      if (calStartDate.getDate() == null) {
         throw new BadFieldException("Start date is empty");
      }
      Date startDate = new Date(calStartDate.getDate().getTime());
      if (calEndDate.getDate() == null) {
         throw new BadFieldException("End date is empty");
      }
      c.setStartDate(startDate);
      Date endDate = new Date(calEndDate.getDate().getTime());
      c.setEndDate(endDate);

      List<Timeslot> timeslots = new ArrayList();
      for (int i = 0; i < slots.getSize(); i++) {
         timeslots.add(slots.get(i));
      }
      c.setTimeslots(timeslots);

      return c;
   }

   private void reset() {
      lblCode.setText("N/A");
      lblName.setText("N/A");
      lblDuration.setText("N/A");
      lblRate.setText("N/A");
      lblClassroom.setText("N/A");
      this.lblStartDate.setText("N/A");
      this.lblEndDate.setText("N/A");
      slots.clear();

      this.txtCode.setText("");
      this.txtName.setText("");
      this.txtDuration.setText("");
      this.txtRate.setText("");
      this.txtDescription.setText("");

      lblMsg.setText("");
   }
}
