/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.robokids.robooffice.desktop.customSwing;

import ca.robokids.robooffice.desktop.loaders.FontsLoader;

/**
 *
 * @author Coldsoft
 */
public class PhoneNumberPanel extends javax.swing.JPanel {

   private final String NUMBER_DELIMITER = "-";
   private final int AREA_CODE_LENGTH = 3;
   private final int MID_NUMBER_LENGTH = 3;
   private final int END_NUMBER_LENGTH = 4;

   /**
    *
    * @return
    */
   public String getPhone() {
      String area = this.txtAreaCode.getText();
      String mid = this.txtMid.getText();
      String end = this.txtEnd.getText();
      if (area.length() < AREA_CODE_LENGTH
         || mid.length() < MID_NUMBER_LENGTH
         || end.length() < END_NUMBER_LENGTH) {
         return "";
      }
      return area + NUMBER_DELIMITER
         + mid + NUMBER_DELIMITER + end;
   }

   /**
    *
    * @param phone
    */
   public void setPhone(String phone) {
      this.txtAreaCode.setText(phone.substring(0, 3));
      this.txtMid.setText(phone.substring(4, 7));
      this.txtEnd.setText(phone.substring(8));
   }

   public void reset() {
      this.txtAreaCode.setText("");
      this.txtMid.setText("");
      this.txtEnd.setText("");
   }

   /**
    * Creates new form PhoneNumberPanel
    */
   public PhoneNumberPanel() {
      initComponents();
      txtAreaCode.setLimit(AREA_CODE_LENGTH);
      txtMid.setLimit(MID_NUMBER_LENGTH);
      txtEnd.setLimit(END_NUMBER_LENGTH);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      txtAreaCode = new ca.robokids.robooffice.desktop.customSwing.IntegerNumberJTextField();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      txtMid = new ca.robokids.robooffice.desktop.customSwing.IntegerNumberJTextField();
      txtEnd = new ca.robokids.robooffice.desktop.customSwing.IntegerNumberJTextField();

      txtAreaCode.setColumns(3);
      txtAreaCode.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      txtAreaCode.setFont(FontsLoader.getTextFieldFont());

      jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("-");

      jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
      jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel2.setText("-");

      txtMid.setColumns(3);
      txtMid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      txtMid.setFont(FontsLoader.getTextFieldFont());
      txtMid.addActionListener(new java.awt.event.ActionListener() {

         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtMidActionPerformed(evt);
         }
      });

      txtEnd.setColumns(4);
      txtEnd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      txtEnd.setFont(FontsLoader.getTextFieldFont());
      txtEnd.addActionListener(new java.awt.event.ActionListener() {

         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtEndActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(txtAreaCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(txtMid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(txtEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)));
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(txtAreaCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel1).addComponent(txtMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel2).addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));
   }// </editor-fold>//GEN-END:initComponents

   private void txtMidActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtMidActionPerformed
   {//GEN-HEADEREND:event_txtMidActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtMidActionPerformed

   private void txtEndActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtEndActionPerformed
   {//GEN-HEADEREND:event_txtEndActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtEndActionPerformed
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private ca.robokids.robooffice.desktop.customSwing.IntegerNumberJTextField txtAreaCode;
   private ca.robokids.robooffice.desktop.customSwing.IntegerNumberJTextField txtEnd;
   private ca.robokids.robooffice.desktop.customSwing.IntegerNumberJTextField txtMid;
   // End of variables declaration//GEN-END:variables

   public boolean isEmpty() {
      String area = this.txtAreaCode.getText();
      String mid = this.txtMid.getText();
      String end = this.txtEnd.getText();
      return (area.length() == 0
         && mid.length() == 0
         && end.length() == 0);
   


   }
}
