/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.robokids.robooffice.desktop.tabs.students.components;

import ca.robokids.exception.BadFieldException;
import ca.robokids.exception.DatabaseException;
import ca.robokids.robooffice.desktop.loaders.FontsLoader;
import ca.robokids.robooffice.desktop.tabs.components.PostalCodeJTextField;
import ca.robokids.robooffice.desktop.util.PopupMessage;
import ca.robokids.robooffice.entity.student.Sex;
import ca.robokids.robooffice.entity.student.Student;
import ca.robokids.robooffice.logic.student.StudentManager;
import ca.robokids.robooffice.logic.usermanagement.UserActivity;
import ca.robokids.robooffice.logic.usermanagement.UserManager;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Coldsoft
 */
public class StudentInfoPanel extends javax.swing.JPanel {

   /**
    * Creates new form StudentInfoPanel
    */
   private Student student;
   private ActiveProgressesPanel parent;
   public StudentInfoPanel(ActiveProgressesPanel parent) {
      initComponents();
      this.parent = parent;
      initTextfieldAutoHightlight();
      
      boolean canEdit = UserActivity.loginUserHasPrivilege("editStudent");
      btnEdit.setEnabled(canEdit);
      btnDelete.setEnabled(canEdit);
      btnToggleStatus.setEnabled(canEdit);
      this.repaint();
   }

   public Student getStudent() {
      return student;
   }

   public void setStudent(Student student) {
      this.student = student;
      if (student != null) {
         populateFields();
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        display = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnToggleStatus = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblBirthdayText = new javax.swing.JLabel();
        lblBirthday = new javax.swing.JLabel();
        lblSchoolText = new javax.swing.JLabel();
        lblSchool = new javax.swing.JLabel();
        lblAddressText = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        lblMom = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblDad = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblHomephone = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblEmergency = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        lblJoinDate = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblCreatedBy = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblHearfrom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblNote = new javax.swing.JTextArea();
        edit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        rdoBoy = new javax.swing.JRadioButton();
        rdoGirl = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtSchool = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cboCity = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtZipcode = new ca.robokids.robooffice.desktop.tabs.components.PostalCodeJTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtMomname = new javax.swing.JTextField();
        txtMomPhone = new ca.robokids.robooffice.desktop.tabs.components.PhoneNumberPanel();
        txtDadname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDadPhone = new ca.robokids.robooffice.desktop.tabs.components.PhoneNumberPanel();
        jLabel11 = new javax.swing.JLabel();
        txtEmergency = new ca.robokids.robooffice.desktop.tabs.components.PhoneNumberPanel();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        lblMsg = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        calBirthday = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        txtHome = new ca.robokids.robooffice.desktop.tabs.components.PhoneNumberPanel();

        setMinimumSize(new java.awt.Dimension(300, 500));
        setPreferredSize(new java.awt.Dimension(235, 400));
        setLayout(new java.awt.CardLayout());

        lblName.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 115, 228));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("First name");

        lblStatus.setFont(FontsLoader.getDynamicLabelFont());
        lblStatus.setForeground(new java.awt.Color(0, 163, 69));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Active");

        btnToggleStatus.setFont(FontsLoader.getButtonFont());
        btnToggleStatus.setText("Make active");
        btnToggleStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToggleStatusActionPerformed(evt);
            }
        });

        lblBirthdayText.setFont(FontsLoader.getStaticLabelFont());
        lblBirthdayText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBirthdayText.setText("His birthday is on");

        lblBirthday.setFont(FontsLoader.getDynamicLabelFont());
        lblBirthday.setText("Birthday");

        lblSchoolText.setFont(FontsLoader.getStaticLabelFont());
        lblSchoolText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSchoolText.setText("School:");

        lblSchool.setFont(FontsLoader.getDynamicLabelFont());
        lblSchool.setText("N/A");

        lblAddressText.setFont(FontsLoader.getStaticLabelFont());
        lblAddressText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddressText.setText("lives at ");

        lblAddress.setFont(FontsLoader.getDynamicLabelFont());
        lblAddress.setText("N/A");

        lblCity.setFont(FontsLoader.getDynamicLabelFont());
        lblCity.setText("N/A");

        jLabel13.setFont(FontsLoader.getStaticLabelFont());
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Mom:");

        lblMom.setFont(FontsLoader.getDynamicLabelFont());
        lblMom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMom.setText("N/A");

        jLabel17.setFont(FontsLoader.getStaticLabelFont());
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Dad:");

        lblDad.setFont(FontsLoader.getDynamicLabelFont());
        lblDad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDad.setText("N/A");

        jLabel21.setFont(FontsLoader.getStaticLabelFont());
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Home:");

        lblHomephone.setFont(FontsLoader.getDynamicLabelFont());
        lblHomephone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHomephone.setText("N/A");

        jLabel23.setFont(FontsLoader.getStaticLabelFont());
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("E-mail:");

        lblEmail.setFont(FontsLoader.getDynamicLabelFont());
        lblEmail.setText("N/A");

        jLabel25.setFont(FontsLoader.getStaticLabelFont());
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Emergency:");

        lblEmergency.setFont(FontsLoader.getDynamicLabelFont());
        lblEmergency.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmergency.setText("N/A");

        jLabel27.setFont(FontsLoader.getStaticLabelFont());
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Joined Robokids since ");

        lblJoinDate.setFont(FontsLoader.getDynamicLabelFont());
        lblJoinDate.setText("N/A");

        jLabel29.setFont(FontsLoader.getStaticLabelFont());
        jLabel29.setText("heard us from");

        jLabel30.setFont(FontsLoader.getStaticLabelFont());
        jLabel30.setText("Registration by");

        lblCreatedBy.setFont(FontsLoader.getDynamicLabelFont());
        lblCreatedBy.setText("N/A");

        btnEdit.setFont(FontsLoader.getButtonFont());
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(FontsLoader.getButtonFont());
        btnDelete.setForeground(new java.awt.Color(255, 0, 51));
        btnDelete.setText("Delete Student");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblHearfrom.setFont(FontsLoader.getDynamicLabelFont());
        lblHearfrom.setText("N/A");

        jLabel1.setFont(FontsLoader.getStaticLabelFont());
        jLabel1.setText("Notes");

        lblNote.setColumns(20);
        lblNote.setEditable(false);
        lblNote.setFont(FontsLoader.getTextFieldFont());
        lblNote.setLineWrap(true);
        lblNote.setRows(3);
        jScrollPane1.setViewportView(lblNote);

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(displayLayout.createSequentialGroup()
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHomephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(displayLayout.createSequentialGroup()
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayLayout.createSequentialGroup()
                        .addComponent(lblEmergency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50))
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(displayLayout.createSequentialGroup()
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblBirthdayText, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(lblSchoolText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddressText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(displayLayout.createSequentialGroup()
                        .addComponent(lblSchool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(lblBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(displayLayout.createSequentialGroup()
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete))
            .addGroup(displayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
            .addGroup(displayLayout.createSequentialGroup()
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJoinDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(displayLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(displayLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHearfrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(displayLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCreatedBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayLayout.createSequentialGroup()
                        .addComponent(btnToggleStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayLayout.createSequentialGroup()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToggleStatus)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBirthdayText)
                    .addComponent(lblBirthday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSchoolText)
                    .addComponent(lblSchool))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddressText)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblMom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblDad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lblHomephone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblEmergency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblJoinDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lblHearfrom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(lblCreatedBy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        add(display, "display");

        jLabel2.setFont(FontsLoader.getStaticLabelFont());
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("First Name");

        jLabel3.setFont(FontsLoader.getStaticLabelFont());
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Last Name");

        txtFirstname.setFont(FontsLoader.getTextFieldFont());

        txtLastname.setFont(FontsLoader.getTextFieldFont());

        buttonGroup1.add(rdoBoy);
        rdoBoy.setFont(FontsLoader.getStaticLabelFont());
        rdoBoy.setSelected(true);
        rdoBoy.setText("Boy");

        buttonGroup1.add(rdoGirl);
        rdoGirl.setFont(FontsLoader.getStaticLabelFont());
        rdoGirl.setText("Girl");

        jLabel4.setFont(FontsLoader.getStaticLabelFont());
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("School");

        txtSchool.setFont(FontsLoader.getTextFieldFont());
        txtSchool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSchoolActionPerformed(evt);
            }
        });

        txtAddress.setFont(FontsLoader.getTextFieldFont());

        jLabel5.setFont(FontsLoader.getStaticLabelFont());
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Address");

        cboCity.setEditable(true);
        cboCity.setFont(FontsLoader.getComboBoxFont());
        cboCity.setModel(new javax.swing.DefaultComboBoxModel(UserManager.CITIES));

        jLabel7.setFont(FontsLoader.getStaticLabelFont());
        jLabel7.setText("Postal Code");

        txtZipcode.setFont(FontsLoader.getTextFieldFont());

        jLabel6.setFont(FontsLoader.getStaticLabelFont());
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Mom's name");

        txtMomname.setFont(FontsLoader.getTextFieldFont());

        txtDadname.setFont(FontsLoader.getTextFieldFont());

        jLabel9.setFont(FontsLoader.getStaticLabelFont());
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Dad's name");

        jLabel11.setFont(FontsLoader.getStaticLabelFont());
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Emergency");

        jLabel12.setFont(FontsLoader.getStaticLabelFont());
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Email");

        txtEmail.setFont(FontsLoader.getTextFieldFont());

        btnSave.setFont(FontsLoader.getButtonFont());
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblMsg.setFont(FontsLoader.getErrorLabelFont());
        lblMsg.setForeground(new java.awt.Color(255, 0, 51));
        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnCancel.setFont(FontsLoader.getButtonFont());
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel14.setFont(FontsLoader.getStaticLabelFont());
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Birthday");

        calBirthday.setFont(FontsLoader.getTextFieldFont());

        jLabel16.setFont(FontsLoader.getStaticLabelFont());
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Home");

        javax.swing.GroupLayout editLayout = new javax.swing.GroupLayout(edit);
        edit.setLayout(editLayout);
        editLayout.setHorizontalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(editLayout.createSequentialGroup()
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addGroup(editLayout.createSequentialGroup()
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editLayout.createSequentialGroup()
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(editLayout.createSequentialGroup()
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoGirl)
                                    .addComponent(rdoBoy)))
                            .addComponent(calBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editLayout.createSequentialGroup()
                                .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboCity, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAddress)
                            .addComponent(txtSchool))
                        .addGap(5, 5, 5)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editLayout.createSequentialGroup()
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editLayout.createSequentialGroup()
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMomPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDadname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDadPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmergency, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMomname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtEmail)))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5))
                .addGap(15, 15, 15))
        );
        editLayout.setVerticalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoBoy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoGirl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCity)
                    .addComponent(jLabel7)
                    .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMomname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMomPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDadname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDadPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmergency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addGap(55, 55, 55))
        );

        add(edit, "edit");
    }// </editor-fold>//GEN-END:initComponents

   private void txtSchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSchoolActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtSchoolActionPerformed

   private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
      this.setEditable(true);
   }//GEN-LAST:event_btnEditActionPerformed

   private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      this.setEditable(false);
   }//GEN-LAST:event_btnCancelActionPerformed

   private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      Student update = null;
      try {
         update = getFields();
      } catch (BadFieldException ex) {
         lblMsg.setText(ex.getMessage());
         return;
      }
      
      if (update != null && update(update))
      {
         
         student = update;
         populateFields();
         setEditable(false);
         parent.studenInfoUpdated();
         
      }
      
   }//GEN-LAST:event_btnSaveActionPerformed

   private void btnToggleStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleStatusActionPerformed
      
         try {
            StudentManager.setStudentStatus(student, !student.isActive());
         } catch (DatabaseException ex) {
            PopupMessage.createErrorPopUp(ex.getMessage(), null);
         }
         student.setActive(!student.isActive());
         setStatusText();
      
   }//GEN-LAST:event_btnToggleStatusActionPerformed

   private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      if (PopupMessage.createDelete(student.toString()))
      {
         if (!PopupMessage.createConfirmPopUp("Deletion of student is not recommended, try set the student inactive. \nDo you still want to delete? all information will be gone.", "Are you sure?"))
            return;
         try {
            StudentManager.deleteStudent(student);
            student = null;
            parent.studenInfoUpdated();
         } catch (DatabaseException ex) {
            PopupMessage.createErrorPopUp(ex.getMessage(), null);
         }
      }
   }//GEN-LAST:event_btnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnToggleStatus;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser calBirthday;
    private javax.swing.JComboBox cboCity;
    private javax.swing.JPanel display;
    private javax.swing.JPanel edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddressText;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblBirthdayText;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCreatedBy;
    private javax.swing.JLabel lblDad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmergency;
    private javax.swing.JLabel lblHearfrom;
    private javax.swing.JLabel lblHomephone;
    private javax.swing.JLabel lblJoinDate;
    private javax.swing.JLabel lblMom;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextArea lblNote;
    private javax.swing.JLabel lblSchool;
    private javax.swing.JLabel lblSchoolText;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JRadioButton rdoBoy;
    private javax.swing.JRadioButton rdoGirl;
    private javax.swing.JTextField txtAddress;
    private ca.robokids.robooffice.desktop.tabs.components.PhoneNumberPanel txtDadPhone;
    private javax.swing.JTextField txtDadname;
    private javax.swing.JTextField txtEmail;
    private ca.robokids.robooffice.desktop.tabs.components.PhoneNumberPanel txtEmergency;
    private javax.swing.JTextField txtFirstname;
    private ca.robokids.robooffice.desktop.tabs.components.PhoneNumberPanel txtHome;
    private javax.swing.JTextField txtLastname;
    private ca.robokids.robooffice.desktop.tabs.components.PhoneNumberPanel txtMomPhone;
    private javax.swing.JTextField txtMomname;
    private javax.swing.JTextField txtSchool;
    private ca.robokids.robooffice.desktop.tabs.components.PostalCodeJTextField txtZipcode;
    // End of variables declaration//GEN-END:variables

   private void setEditable(boolean b) {
      String card = new String();
      if (b) {
         card = "edit";
      } else {
         card = "display";
      }
      CardLayout c = (CardLayout) this.getLayout();
      c.show(this, card);
   }

   private void setStatusText()
   {
      //Set the status label's text and color on display panel
      if (student.isProspective()) {
         this.lblStatus.setText("Prospective student");
         btnToggleStatus.setVisible(false);
      } else if (student.isActive()) {
         this.btnToggleStatus.setText("Set inactive");
         this.lblStatus.setText("Active");
         lblStatus.setForeground(new Color(0, 163, 69));
      } else {
         this.btnToggleStatus.setText("Set active");
         this.lblStatus.setText("Inactive");
         lblStatus.setForeground(new Color(102, 102, 102));
      }


   }
   private void populateFields() {
      this.lblName.setText(student.toString());
      this.lblName.setForeground(student.getSex().getColor());
      this.btnEdit.setToolTipText("Information last modified on " + student.getModifiedDateString());
      this.txtFirstname.setText(student.getFirstName());
      this.txtLastname.setText(student.getLastName());
      if (student.getSex() == Sex.BOY)
         rdoBoy.setSelected(true);
      else
         rdoGirl.setSelected(true);

      setStatusText();
      
      lblBirthdayText.setText(student.getSex().getPossessivePronoun() + " birthday is on ");
      lblBirthday.setText(student.getBirthdayString());
      this.calBirthday.setDate(student.getBirthday());

      lblSchoolText.setText(student.getSex().getPronoun() + " goes to ");
      lblSchool.setText(student.getSchool());
      this.txtSchool.setText(student.getSchool());

      lblAddressText.setText(student.getSex().getPronoun() + " lives at ");
      lblAddress.setText(student.getAddress());
      this.txtAddress.setText(student.getAddress());
      lblCity.setText(student.getCity() + " " + student.getZipcode());
      this.cboCity.setSelectedItem(student.getCity());;
      this.txtZipcode.setText(student.getZipcode());

      lblMom.setText(student.getMotherPhone() + " " + student.getMother());
      this.txtMomname.setText(student.getMother());
      this.txtMomPhone.setPhone(student.getMotherPhone());

      lblDad.setText(student.getFatherPhone() + " " + student.getFather());
      this.txtDadname.setText(student.getFather());
      this.txtDadPhone.setPhone(student.getFatherPhone());

      lblHomephone.setText(student.getHomePhone());
      this.txtHome.setPhone(student.getHomePhone());

      lblEmergency.setText(student.getEmergency());
      this.txtEmergency.setPhone(student.getEmergency());

      lblEmail.setText(student.getEmail());
      this.txtEmail.setText(student.getEmail());

      lblJoinDate.setText(student.getJoinDateString());
      lblHearfrom.setText(student.getHearFrom());
      lblCreatedBy.setText(student.getCreated_by().toString());

      lblNote.setText(student.getNotes());


   }

   private void initTextfieldAutoHightlight() {
      for (final Component c : this.edit.getComponents()) {
         if (c instanceof JTextField) {
            final JTextField textField = (JTextField) c;
            textField.addFocusListener(new java.awt.event.FocusAdapter() {
               @Override
               public void focusGained(java.awt.event.FocusEvent evt) {
                  textField.setSelectionStart(0);
                  textField.setSelectionEnd(textField.getText().length());
               }
            });
         }
      }
   }

   private boolean update(Student s) {
      try {
         s.setStudent_id(student.getStudent_id());
         s.setCreated_by(student.getCreated_by());
         s.setDeleted(student.isDeleted());
         s.setActive(student.isActive());
         s.setProspective(student.isProspective());
         s.setJoinDate(student.getJoinDate());
         s.setNotes(student.getNotes());
         s.setHearFrom((student.getHearFrom()));
         StudentManager.modifyStudent(s);
         return true;
      } catch (BadFieldException ex) {
         lblMsg.setText(ex.getMessage());
         return false;
      } catch (DatabaseException ex) {
         PopupMessage.createErrorPopUp(ex.getMessage(), null);
         return false;
      }

   }
   private Student getFields() throws BadFieldException {
      Student s = new Student();
      s.setFirstName(txtFirstname.getText().trim());
      s.setLastName(txtLastname.getText().trim());
      if (rdoBoy.isSelected()) {
         s.setSex(Sex.BOY);

      } else {
         s.setSex(Sex.GIRL);
      }
      Date date = calBirthday.getDate();
      if (date == null) {
         throw new BadFieldException("Birthday is incorrectly filled.");
      }

      java.sql.Date birthday = new java.sql.Date(date.getTime());
      s.setBirthday(birthday);
      s.setAddress(txtAddress.getText().trim());
      String city = (String) cboCity.getSelectedItem();
      s.setCity(city);
      s.setZipcode(txtZipcode.getText().trim());
      s.setSchool(txtSchool.getText().trim());
      //Contacts
      s.setMother(txtMomname.getText().trim());
      s.setFather(txtDadname.getText().trim());

      String txtPhone = txtMomPhone.getPhone();
      if (txtPhone == null && !this.txtMomPhone.isEmpty()) {
         throw new BadFieldException("Mother's phone number format incorrect");
      }
      s.setMotherPhone(txtPhone);

      txtPhone = this.txtDadPhone.getPhone();
      if (txtPhone == null && !this.txtDadPhone.isEmpty()) {
         throw new BadFieldException("Father's phone number format incorrect");
      }
      s.setFatherPhone(txtPhone);

      txtPhone = this.txtHome.getPhone();
      if (txtPhone == null && !this.txtHome.isEmpty()) {
         throw new BadFieldException("Home phone number format incorrect");
      }
      s.setHomePhone(txtPhone);

      txtPhone = this.txtEmergency.getPhone();
      if (txtPhone == null && !this.txtEmergency.isEmpty()) {
         throw new BadFieldException("Emergency phone number format incorrect");
      }
      s.setEmergency(txtPhone);
      s.setEmail(txtEmail.getText().trim());
      return s;
   }
}
