/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.robokids.robooffice.desktop.tabs.finance.components;

import ca.robokids.exception.DatabaseException;
import ca.robokids.robooffice.desktop.loaders.FontsLoader;
import ca.robokids.robooffice.desktop.util.PopupMessage;
import ca.robokids.robooffice.entity.finance.newpayment.CoursePaymentEntry;
import ca.robokids.robooffice.entity.finance.newpayment.CoursePaymentEntry.CoursePaymentType;
import ca.robokids.robooffice.entity.schoolmetadata.Course;
import ca.robokids.robooffice.entity.schoolmetadata.Timeslot;
import ca.robokids.robooffice.entity.student.CourseProgress;
import ca.robokids.robooffice.logic.finance.TaxManager;
import ca.robokids.robooffice.logic.schoolsettings.SchoolManager;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Coldsoft
 */
public class CoursePaymentSettingPanel extends javax.swing.JPanel {

   List<Course> courses;
   List<CourseProgress> courseProgress;
   DefaultComboBoxModel<Course> coursesModel = new DefaultComboBoxModel();
   DefaultComboBoxModel<CourseProgress> progressModel = new DefaultComboBoxModel();
   DefaultListModel<Timeslot> timeslotsModel = new DefaultListModel();
   DefaultComboBoxModel<Timeslot> timeslotsComboModel = new DefaultComboBoxModel();
   SubtotalPanel pnlSubTotal;
   CoursePaymentEntry paymentEntry;
   /**
    * Creates new form CoursePaymentSettingPanel
    */
   public CoursePaymentSettingPanel() {
      initComponents();
      initCourseTypePanel();
   }
   
   public CoursePaymentSettingPanel(CoursePaymentEntry paymentEntry)
   {
      this();
      this.paymentEntry = paymentEntry;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseType = new javax.swing.JPanel();
        courseInfoPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblRate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTimeslot = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        lblClassroom = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cboCourses = new javax.swing.JComboBox();
        btnBacktoChooser = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        radiobuttonsPanel = new javax.swing.JPanel();
        rdoPayAdvance = new javax.swing.JRadioButton();
        rdoLevelup = new javax.swing.JRadioButton();
        rdoContinue = new javax.swing.JRadioButton();
        cboCurrentProgresses = new javax.swing.JComboBox();
        rdoNewCourse = new javax.swing.JRadioButton();
        lblNewCourse = new javax.swing.JLabel();
        lblPayinadvance = new javax.swing.JLabel();
        lblLevelup = new javax.swing.JLabel();
        courseSetting = new javax.swing.JPanel();
        pnlLastCourse = new javax.swing.JPanel();
        lblLastCourse = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblProgress = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblTimeslot = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblCredit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cboTimeslot = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        calStart = new com.toedter.calendar.JDateChooser();
        calExpire = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        spinWeeks = new com.toedter.components.JSpinField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtAmount = new ca.robokids.robooffice.desktop.tabs.components.CurrencyJTextField();
        txtAvailableCredit = new ca.robokids.robooffice.desktop.tabs.components.CurrencyJTextField();
        jLabel31 = new javax.swing.JLabel();
        txtAmountCalculation = new javax.swing.JLabel();
        subTotalPanel = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Rate:");

        lblRate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblRate.setText("$000.00");

        lstTimeslot.setFont(FontsLoader.getBigListFont());
        lstTimeslot.setModel(timeslotsModel);
        lstTimeslot.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTimeslot.setEnabled(false);
        jScrollPane1.setViewportView(lstTimeslot);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Duration:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Classroom:");
        jLabel9.setToolTipText("");

        lblTax.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblTax.setText("+ 12% HST");

        lblDuration.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblDuration.setText("0 minutes");

        lblClassroom.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblClassroom.setText("jLabel12");
        lblClassroom.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jScrollPane2.setBorder(null);

        txtDescription.setColumns(20);
        txtDescription.setEditable(false);
        txtDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        jScrollPane2.setViewportView(txtDescription);

        javax.swing.GroupLayout courseInfoPanelLayout = new javax.swing.GroupLayout(courseInfoPanel);
        courseInfoPanel.setLayout(courseInfoPanelLayout);
        courseInfoPanelLayout.setHorizontalGroup(
            courseInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(courseInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(courseInfoPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(courseInfoPanelLayout.createSequentialGroup()
                        .addGroup(courseInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(courseInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(courseInfoPanelLayout.createSequentialGroup()
                                .addComponent(lblRate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTax, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addComponent(lblDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblClassroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        courseInfoPanelLayout.setVerticalGroup(
            courseInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(courseInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(courseInfoPanelLayout.createSequentialGroup()
                        .addGroup(courseInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblRate)
                            .addComponent(lblTax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(courseInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblDuration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(courseInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblClassroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(FontsLoader.getStaticLabelFont());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Select a Course");

        cboCourses.setFont(FontsLoader.getComboBoxFont());
        cboCourses.setMaximumRowCount(12);
        cboCourses.setModel(coursesModel);
        cboCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCoursesActionPerformed(evt);
            }
        });

        btnBacktoChooser.setFont(FontsLoader.getButtonFont());
        btnBacktoChooser.setText("Back");
        btnBacktoChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacktoChooserActionPerformed(evt);
            }
        });

        btnNext.setFont(FontsLoader.getButtonFont());
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        rdoPayAdvance.setFont(FontsLoader.getStaticLabelFont());
        rdoPayAdvance.setSelected(true);
        rdoPayAdvance.setText("Pay in advance");
        rdoPayAdvance.setEnabled(false);

        rdoLevelup.setFont(FontsLoader.getStaticLabelFont());
        rdoLevelup.setText("Level-up from current course");
        rdoLevelup.setEnabled(false);

        rdoContinue.setFont(FontsLoader.getStaticLabelFont());
        rdoContinue.setText("Continue from");
        rdoContinue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdoContinueStateChanged(evt);
            }
        });

        cboCurrentProgresses.setFont(FontsLoader.getComboBoxFont());
        cboCurrentProgresses.setModel(this.progressModel);
        cboCurrentProgresses.setEnabled(false);
        cboCurrentProgresses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCurrentProgressesActionPerformed(evt);
            }
        });

        rdoNewCourse.setFont(FontsLoader.getStaticLabelFont());
        rdoNewCourse.setSelected(true);
        rdoNewCourse.setText("New Course");

        lblNewCourse.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lblNewCourse.setText("（新课程）");

        lblPayinadvance.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lblPayinadvance.setText("（预付款）");
        lblPayinadvance.setEnabled(false);

        lblLevelup.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        lblLevelup.setText("（提前升级）");
        lblLevelup.setEnabled(false);

        javax.swing.GroupLayout radiobuttonsPanelLayout = new javax.swing.GroupLayout(radiobuttonsPanel);
        radiobuttonsPanel.setLayout(radiobuttonsPanelLayout);
        radiobuttonsPanelLayout.setHorizontalGroup(
            radiobuttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radiobuttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(radiobuttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(radiobuttonsPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(radiobuttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(radiobuttonsPanelLayout.createSequentialGroup()
                                .addComponent(rdoLevelup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLevelup, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(radiobuttonsPanelLayout.createSequentialGroup()
                                .addComponent(rdoPayAdvance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPayinadvance, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))))
                    .addGroup(radiobuttonsPanelLayout.createSequentialGroup()
                        .addComponent(rdoNewCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNewCourse)
                        .addGap(132, 132, 132))
                    .addGroup(radiobuttonsPanelLayout.createSequentialGroup()
                        .addComponent(rdoContinue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCurrentProgresses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        radiobuttonsPanelLayout.setVerticalGroup(
            radiobuttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radiobuttonsPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(radiobuttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNewCourse)
                    .addComponent(lblNewCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(radiobuttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoContinue)
                    .addComponent(cboCurrentProgresses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(radiobuttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdoPayAdvance)
                    .addComponent(lblPayinadvance, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(radiobuttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoLevelup)
                    .addComponent(lblLevelup, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout courseTypeLayout = new javax.swing.GroupLayout(courseType);
        courseType.setLayout(courseTypeLayout);
        courseTypeLayout.setHorizontalGroup(
            courseTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(courseTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(courseTypeLayout.createSequentialGroup()
                        .addComponent(courseInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(courseTypeLayout.createSequentialGroup()
                        .addGroup(courseTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(courseTypeLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(courseTypeLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(courseTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(courseTypeLayout.createSequentialGroup()
                                        .addComponent(btnBacktoChooser)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnNext))
                                    .addComponent(radiobuttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 55, Short.MAX_VALUE))))
        );
        courseTypeLayout.setVerticalGroup(
            courseTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiobuttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(courseTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBacktoChooser)
                    .addComponent(btnNext))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        add(courseType, "courseType");

        pnlLastCourse.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Course Infomation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblLastCourse.setText("Course Name");

        jLabel4.setText("Progress:");

        lblProgress.setText("N/A");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Start Date:");

        lblStartDate.setText("N/A");

        lblTimeslot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTimeslot.setText("Section");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("End Date:");

        lblEndDate.setText("N/A");

        jLabel14.setText("Credit left:");

        lblCredit.setText("N/A");

        javax.swing.GroupLayout pnlLastCourseLayout = new javax.swing.GroupLayout(pnlLastCourse);
        pnlLastCourse.setLayout(pnlLastCourseLayout);
        pnlLastCourseLayout.setHorizontalGroup(
            pnlLastCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLastCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLastCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTimeslot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlLastCourseLayout.createSequentialGroup()
                        .addGroup(pnlLastCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLastCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCredit, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLastCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLastCourseLayout.createSequentialGroup()
                        .addComponent(lblLastCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlLastCourseLayout.createSequentialGroup()
                        .addGroup(pnlLastCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLastCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLastCourseLayout.createSequentialGroup()
                                .addComponent(lblEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(lblStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        pnlLastCourseLayout.setVerticalGroup(
            pnlLastCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLastCourseLayout.createSequentialGroup()
                .addGroup(pnlLastCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastCourse)
                    .addComponent(lblTimeslot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLastCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblProgress)
                    .addComponent(jLabel7)
                    .addComponent(lblStartDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLastCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblEndDate)
                    .addComponent(jLabel14)
                    .addComponent(lblCredit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Paying for ");

        lblCourse.setText("N/A");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Time:");

        cboTimeslot.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel19.setText("Start Date:");

        jLabel20.setText("to");

        jLabel21.setText("Weeks:");

        spinWeeks.setMaximum(100);
        spinWeeks.setMinimum(0);

        jLabel22.setText("Amount");

        jLabel23.setText("Available Credit");

        jLabel29.setText("$");

        jLabel31.setText("$");

        txtAmountCalculation.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(calStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboTimeslot, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinWeeks, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calExpire, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98))))
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAmountCalculation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAvailableCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(cboTimeslot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addComponent(spinWeeks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(calStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(calExpire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtAmountCalculation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtAvailableCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)))
        );

        subTotalPanel.setLayout(new javax.swing.BoxLayout(subTotalPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout courseSettingLayout = new javax.swing.GroupLayout(courseSetting);
        courseSetting.setLayout(courseSettingLayout);
        courseSettingLayout.setHorizontalGroup(
            courseSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseSettingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(courseSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subTotalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLastCourse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        courseSettingLayout.setVerticalGroup(
            courseSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseSettingLayout.createSequentialGroup()
                .addComponent(pnlLastCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subTotalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
        );

        add(courseSetting, "courseSetting");
    }// </editor-fold>//GEN-END:initComponents

   private void cboCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCoursesActionPerformed
      int index = cboCourses.getSelectedIndex();
      if (index > -1) {
         this.courseInfoPanel.setVisible(true);
         this.updateCourseOverviewPanel(coursesModel.getElementAt(index));
         this.rdoNewCourse.setEnabled(true);
         this.rdoContinue.setEnabled(true);
         this.lblNewCourse.setEnabled(true);
         this.btnNext.setEnabled(true);
      } else {
         updateCourseOverviewPanel(null);
      }
   }//GEN-LAST:event_cboCoursesActionPerformed

   private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
      initCourseSettingPanel();
      switchTo("courseSetting");
   }//GEN-LAST:event_btnNextActionPerformed

   private void rdoContinueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdoContinueStateChanged
      if (rdoContinue.isSelected()) {
         this.cboCurrentProgresses.setEnabled(true);
         if (cboCurrentProgresses.getSelectedIndex() > -1) {
            this.rdoPayAdvance.setEnabled(true);
            this.rdoLevelup.setEnabled(true);
            this.lblPayinadvance.setEnabled(true);
            this.lblLevelup.setEnabled(true);
         }
      } else {
         this.rdoPayAdvance.setEnabled(false);
         this.rdoLevelup.setEnabled(false);
         this.lblPayinadvance.setEnabled(false);
         this.lblLevelup.setEnabled(false);
         this.cboCurrentProgresses.setSelectedIndex(-1);
      }
   }//GEN-LAST:event_rdoContinueStateChanged

   private void cboCurrentProgressesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCurrentProgressesActionPerformed

      if (cboCurrentProgresses.getSelectedIndex() > -1) {
         this.rdoPayAdvance.setEnabled(true);
         this.rdoLevelup.setEnabled(true);
         this.lblPayinadvance.setEnabled(true);
         this.lblLevelup.setEnabled(true);
      } else {
         this.rdoPayAdvance.setEnabled(false);
         this.rdoLevelup.setEnabled(false);
         this.lblPayinadvance.setEnabled(false);
         this.lblLevelup.setEnabled(false);
      }
   }//GEN-LAST:event_cboCurrentProgressesActionPerformed

   private void btnBacktoChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktoChooserActionPerformed
      paymentEntry = null;
      switchTo("chooseType");
   }//GEN-LAST:event_btnBacktoChooserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBacktoChooser;
    private javax.swing.JButton btnNext;
    private com.toedter.calendar.JDateChooser calExpire;
    private com.toedter.calendar.JDateChooser calStart;
    private javax.swing.JComboBox cboCourses;
    private javax.swing.JComboBox cboCurrentProgresses;
    private javax.swing.JComboBox cboTimeslot;
    private javax.swing.JPanel courseInfoPanel;
    private javax.swing.JPanel courseSetting;
    private javax.swing.JPanel courseType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClassroom;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblCredit;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblLastCourse;
    private javax.swing.JLabel lblLevelup;
    private javax.swing.JLabel lblNewCourse;
    private javax.swing.JLabel lblPayinadvance;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblRate;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTimeslot;
    private javax.swing.JList lstTimeslot;
    private javax.swing.JPanel pnlLastCourse;
    private javax.swing.JPanel radiobuttonsPanel;
    private javax.swing.JRadioButton rdoContinue;
    private javax.swing.JRadioButton rdoLevelup;
    private javax.swing.JRadioButton rdoNewCourse;
    private javax.swing.JRadioButton rdoPayAdvance;
    private com.toedter.components.JSpinField spinWeeks;
    private javax.swing.JPanel subTotalPanel;
    private ca.robokids.robooffice.desktop.tabs.components.CurrencyJTextField txtAmount;
    private javax.swing.JLabel txtAmountCalculation;
    private ca.robokids.robooffice.desktop.tabs.components.CurrencyJTextField txtAvailableCredit;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables

   private void initCourseTypePanel() {
      //Load the all courses combobox
      try {
         courses = SchoolManager.loadAllCourses();
      } catch (DatabaseException ex) {
         PopupMessage.createErrorPopUp(ex.getMessage(), null);
         this.switchTo("choose");
         return;
      }
      coursesModel.removeAllElements();
      for (Course c : courses) {
         coursesModel.addElement(c);
      }

      cboCourses.setSelectedIndex(-1);
   }
   
   private void switchTo(String card)
   {
      CardLayout c = (CardLayout) this.getLayout();
      c.show(this, card);
   }
   private void updateCourseOverviewPanel(Course c) {
      
      timeslotsModel.removeAllElements();
      timeslotsComboModel.removeAllElements();
      if (c == null) // if no course is being selected
      {

         lblClassroom.setText("N/A");
         lblDuration.setText("N/A");
         lblRate.setText("N/A");
         txtDescription.setText(" ");
         lblTax.setText(" ");
         
         courseInfoPanel.setVisible(false);
         
         for (Component com : radiobuttonsPanel.getComponents())
         {
            com.setEnabled(false);
         }
         this.btnNext.setEnabled(false);
         return;
      }

      this.lblClassroom.setText(c.getClassroom().getName());
      this.lblDuration.setText(String.valueOf(c.getDuration()) + " minutes");
      this.lblRate.setText(c.getRateString());
      this.txtDescription.setText(c.getDescription());
      if (c.hasTax()) {
         try {
            this.lblTax.setText(" +" + String.valueOf(TaxManager.getCurrentTax()) + "% tax");
         } catch (DatabaseException ex) {
            PopupMessage.createErrorPopUp(ex.getMessage() + "\nerror loading tax", null);
            this.lblTax.setText("+ tax");
         }
      } else {
         lblTax.setText(" no tax");
      }
      //initial timeslot list
      
      for (Timeslot t : c.getTimeslots()) {
         timeslotsModel.addElement(t);
         timeslotsComboModel.addElement(t);
      }




   }

   private void initCourseSettingPanel() {
      
      
      // If paying a new course instead of changing setting of existing entry
      if (paymentEntry == null)
      {
         paymentEntry = new CoursePaymentEntry();
         setCoursePaymentType(paymentEntry);
         Course c = null;
         int index = cboCourses.getSelectedIndex();
         if (index > -1) {
            c = courses.get(index);
         }
         paymentEntry.setCourse(c);
         lblCourse.setText(c.toString());
         
         try {
            CoursePaymentEntry.setDefaultValues(paymentEntry);
         } catch (DatabaseException ex) {
            Logger.getLogger(CoursePaymentSettingPanel.class.getName()).log(Level.SEVERE, null, ex);
         }        
         initLastCoursePanel();
         calStart.setDate(paymentEntry.getStartDate());
         calExpire.setDate(paymentEntry.getExpireDate());
         
      }
      

      subTotalPanel.add(pnlSubTotal);
      
   }
   private void setCoursePaymentType(CoursePaymentEntry entry) {
      if (this.rdoLevelup.isSelected())
      {
         entry.setType(CoursePaymentEntry.CoursePaymentType.LEVELUP);
         entry.setLastProgress(progressModel.getElementAt(cboCurrentProgresses.getSelectedIndex()));
      }else if (this.rdoPayAdvance.isSelected())
      {
         entry.setType(CoursePaymentEntry.CoursePaymentType.PAY_ADVANCE);
         entry.setLastProgress(progressModel.getElementAt(cboCurrentProgresses.getSelectedIndex()));
      }
      entry.setType(CoursePaymentEntry.CoursePaymentType.NEW_COURSE);
      entry.setLastProgress(null);
   }

   private void initLastCoursePanel() {

      if (paymentEntry.getType() == CoursePaymentType.NEW_COURSE){
         pnlLastCourse.setVisible(false);
      }
      CourseProgress lastProgress = paymentEntry.getLastProgress();
      lblLastCourse.setText(lastProgress.getSection().getCourse().toString());
      lblTimeslot.setText(lastProgress.getSection().getTimeslot().toString());
      lblProgress.setText(lastProgress.getProgress() + "/" + lastProgress.getTotalClass());
      lblStartDate.setText(lastProgress.getStartDateString());
      lblEndDate.setText(lastProgress.getEndDateString());
      lblCredit.setText(lastProgress.getAvailableCreditString());
   }
   
}
