/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.robokids.robooffice.desktop.tabs.school;

import ca.robokids.exception.BadFieldException;
import ca.robokids.exception.DatabaseException;
import ca.robokids.robooffice.desktop.loaders.FontsLoader;
import ca.robokids.robooffice.desktop.tabs.Tab;
import ca.robokids.robooffice.desktop.util.PopupMessage;
import ca.robokids.robooffice.entity.schoolmetadata.Fee;
import ca.robokids.robooffice.logic.finance.FinanceSetting;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Coldsoft
 */
public class FinanceSettingsTab extends javax.swing.JPanel implements Tab{

   /**
    * Creates new form FinanceSettingsTab
    */
   
   Fee fee;
   DefaultListModel<Fee> feeModel = new DefaultListModel();
   public FinanceSettingsTab() {
      initComponents();
      initialize();
      switchCard("display");
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        center = new javax.swing.JPanel();
        pnlFinanceSetting = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTax = new ca.robokids.robooffice.desktop.customSwing.CurrencyJTextField();
        btnSaveTax = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFees = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        panelFeeInfo = new javax.swing.JPanel();
        edit = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chkTax = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        txtName = new javax.swing.JTextField();
        txtRate = new ca.robokids.robooffice.desktop.customSwing.CurrencyJTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        add = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        chkTaxAdd = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescriptionAdd = new javax.swing.JTextArea();
        txtNameAdd = new javax.swing.JTextField();
        txtRateAdd = new ca.robokids.robooffice.desktop.customSwing.CurrencyJTextField();
        jLabel15 = new javax.swing.JLabel();
        btnSaveAdd = new javax.swing.JButton();
        btnCancelAdd = new javax.swing.JButton();
        display = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkHasTax = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblDescription = new javax.swing.JTextArea();
        lblRate = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDateCreated = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblCreatedBy = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        btnAddNew = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        pnlFinanceSetting.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Finance Setting", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, FontsLoader.getTitleBorderFont()));

        jLabel1.setFont(FontsLoader.getStaticLabelFont());
        jLabel1.setText("Tax(%)");

        txtTax.setFont(FontsLoader.getTextFieldFont());

        btnSaveTax.setFont(FontsLoader.getButtonFont());
        btnSaveTax.setText("Save");
        btnSaveTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFinanceSettingLayout = new javax.swing.GroupLayout(pnlFinanceSetting);
        pnlFinanceSetting.setLayout(pnlFinanceSettingLayout);
        pnlFinanceSettingLayout.setHorizontalGroup(
            pnlFinanceSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinanceSettingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFinanceSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFinanceSettingLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFinanceSettingLayout.createSequentialGroup()
                        .addGap(0, 39, Short.MAX_VALUE)
                        .addComponent(btnSaveTax)))
                .addContainerGap())
        );
        pnlFinanceSettingLayout.setVerticalGroup(
            pnlFinanceSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinanceSettingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFinanceSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveTax)
                .addContainerGap())
        );

        lstFees.setFont(FontsLoader.getBigListFont());
        lstFees.setModel(feeModel);
        lstFees.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstFeesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstFees);

        jLabel2.setFont(FontsLoader.getStaticLabelFont());
        jLabel2.setText("Fees");

        panelFeeInfo.setLayout(new java.awt.CardLayout());

        jLabel8.setFont(FontsLoader.getStaticLabelFont());
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Name:");

        jLabel9.setFont(FontsLoader.getStaticLabelFont());
        jLabel9.setText("Rate:");

        chkTax.setFont(FontsLoader.getStaticLabelFont());
        chkTax.setText("has tax");
        chkTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTaxActionPerformed(evt);
            }
        });

        jLabel10.setFont(FontsLoader.getStaticLabelFont());
        jLabel10.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setFont(FontsLoader.getTextFieldFont());
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        jScrollPane3.setViewportView(txtDescription);

        txtName.setFont(FontsLoader.getTextFieldFont());

        txtRate.setFont(FontsLoader.getTextFieldFont());
        txtRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRateActionPerformed(evt);
            }
        });

        jLabel3.setText("$");

        btnSave.setFont(FontsLoader.getButtonFont());
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(FontsLoader.getButtonFont());
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editLayout = new javax.swing.GroupLayout(edit);
        edit.setLayout(editLayout);
        editLayout.setHorizontalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editLayout.createSequentialGroup()
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel10))
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkTax))
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(editLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addGroup(editLayout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel)))))
                .addContainerGap())
        );
        editLayout.setVerticalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTax)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addGap(43, 43, 43))
        );

        panelFeeInfo.add(edit, "edit");

        jLabel12.setFont(FontsLoader.getStaticLabelFont());
        jLabel12.setText("Name:");

        jLabel13.setFont(FontsLoader.getStaticLabelFont());
        jLabel13.setText("Rate:");

        chkTaxAdd.setFont(FontsLoader.getStaticLabelFont());
        chkTaxAdd.setText("has tax");
        chkTaxAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTaxAddActionPerformed(evt);
            }
        });

        jLabel14.setFont(FontsLoader.getStaticLabelFont());
        jLabel14.setText("Description");

        jScrollPane4.setEnabled(false);

        txtDescriptionAdd.setColumns(20);
        txtDescriptionAdd.setFont(FontsLoader.getTextFieldFont());
        txtDescriptionAdd.setLineWrap(true);
        txtDescriptionAdd.setRows(5);
        jScrollPane4.setViewportView(txtDescriptionAdd);

        txtNameAdd.setFont(FontsLoader.getTextFieldFont());

        txtRateAdd.setFont(FontsLoader.getTextFieldFont());
        txtRateAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRateAddActionPerformed(evt);
            }
        });

        jLabel15.setText("$");

        btnSaveAdd.setFont(FontsLoader.getButtonFont());
        btnSaveAdd.setText("Add");
        btnSaveAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAddActionPerformed(evt);
            }
        });

        btnCancelAdd.setFont(FontsLoader.getButtonFont());
        btnCancelAdd.setText("Cancel");
        btnCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
        add.setLayout(addLayout);
        addLayout.setHorizontalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addLayout.createSequentialGroup()
                        .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel14))
                            .addGroup(addLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkTaxAdd))
                                    .addComponent(txtNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(addLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addGroup(addLayout.createSequentialGroup()
                                .addComponent(btnSaveAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelAdd)))))
                .addContainerGap())
        );
        addLayout.setVerticalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTaxAdd)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelAdd)
                    .addComponent(btnSaveAdd))
                .addGap(48, 48, 48))
        );

        panelFeeInfo.add(add, "add");

        display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel4.setFont(FontsLoader.getStaticLabelFont());
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Name:");

        jLabel5.setFont(FontsLoader.getStaticLabelFont());
        jLabel5.setText("Description");

        jLabel6.setFont(FontsLoader.getStaticLabelFont());
        jLabel6.setText("Date Created/Modified:");

        chkHasTax.setFont(FontsLoader.getStaticLabelFont());
        chkHasTax.setText("has tax");
        chkHasTax.setEnabled(false);

        jLabel7.setFont(FontsLoader.getStaticLabelFont());
        jLabel7.setText("Rate:");

        lblDescription.setColumns(20);
        lblDescription.setEditable(false);
        lblDescription.setFont(FontsLoader.getTextFieldFont());
        lblDescription.setLineWrap(true);
        lblDescription.setRows(5);
        lblDescription.setEnabled(false);
        lblDescription.setFocusable(false);
        jScrollPane2.setViewportView(lblDescription);

        lblRate.setFont(FontsLoader.getDynamicLabelFont());
        lblRate.setText("N/A");

        lblName.setFont(FontsLoader.getDynamicLabelFont());
        lblName.setText("N/A");

        lblDateCreated.setFont(FontsLoader.getDynamicLabelFont());
        lblDateCreated.setText("N/A");

        jLabel11.setFont(FontsLoader.getStaticLabelFont());
        jLabel11.setText("By");

        lblCreatedBy.setFont(FontsLoader.getDynamicLabelFont());
        lblCreatedBy.setText("N/A");

        btnEdit.setFont(FontsLoader.getButtonFont());
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(FontsLoader.getButtonFont());
        btnDelete.setForeground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayLayout.createSequentialGroup()
                        .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(displayLayout.createSequentialGroup()
                                .addComponent(lblRate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chkHasTax))))
                    .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(displayLayout.createSequentialGroup()
                            .addComponent(btnEdit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(displayLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreatedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRate)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkHasTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lblCreatedBy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        panelFeeInfo.add(display, "display");

        lblMsg.setFont(FontsLoader.getErrorLabelFont());

        btnAddNew.setFont(FontsLoader.getButtonFont());
        btnAddNew.setText("Add New Fee");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerLayout.createSequentialGroup()
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(centerLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddNew))
                            .addGroup(centerLayout.createSequentialGroup()
                                .addComponent(pnlFinanceSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 103, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFeeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        centerLayout.setVerticalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(centerLayout.createSequentialGroup()
                        .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(centerLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(btnAddNew))
                            .addGroup(centerLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(pnlFinanceSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(panelFeeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 103;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 42, 21, 36);
        add(center, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

   private void chkTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTaxActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_chkTaxActionPerformed

   private void txtRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRateActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtRateActionPerformed

   private void chkTaxAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTaxAddActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_chkTaxAddActionPerformed

   private void txtRateAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRateAddActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtRateAddActionPerformed

   private void lstFeesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFeesValueChanged
      int index = lstFees.getSelectedIndex();
      if (index > -1 ){
         switchCard("display");
         
         setFee(feeModel.getElementAt(index)); 
         btnEdit.setEnabled(true);
         btnDelete.setEnabled(true);
      }
      
   }//GEN-LAST:event_lstFeesValueChanged

   private void btnSaveTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTaxActionPerformed
      float tax;
      try
      {
         tax = Float.valueOf(txtTax.getText());
      }catch(Exception e)
      {
         errorMsg("tax format is wrong.");
         return;
      }
      try {
         FinanceSetting.setTax(tax);
         Msg("tax updated");
      } catch (DatabaseException ex) {
         PopupMessage.createErrorPopUp(ex.getMessage(), null);
      }
      refresh();
   }//GEN-LAST:event_btnSaveTaxActionPerformed

   private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
      switchCard("add");
   }//GEN-LAST:event_btnAddNewActionPerformed

   private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
      switchCard("edit");
   }//GEN-LAST:event_btnEditActionPerformed

   private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      if (fee != null)
      {
         try {
            FinanceSetting.deleteFee(fee);
         } catch (DatabaseException ex) {
            PopupMessage.createErrorPopUp(ex.getMessage(), null);
         }
         refresh();
      }
   }//GEN-LAST:event_btnDeleteActionPerformed

   private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      Fee temp = getEditFields();
      
         temp.setFee_id(fee.getFee_id());
      try {
         FinanceSetting.modifyFee(temp);
         refresh();
      } catch (BadFieldException ex) {
         errorMsg(ex.getMessage());
      } catch (DatabaseException ex) {
         PopupMessage.createErrorPopUp(ex.getMessage(), null);
      }
      
   }//GEN-LAST:event_btnSaveActionPerformed

   private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      switchCard("display");
   }//GEN-LAST:event_btnCancelActionPerformed

   private void btnCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddActionPerformed
      switchCard("display");
   }//GEN-LAST:event_btnCancelAddActionPerformed

   private void btnSaveAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAddActionPerformed
      Fee temp = getAddFields();
      try {
         FinanceSetting.createFee(temp);
         refresh();
      } catch (BadFieldException ex) {
         errorMsg(ex.getMessage());
      } catch (DatabaseException ex) {
         PopupMessage.createErrorPopUp(ex.getMessage(), null);
      }
   }//GEN-LAST:event_btnSaveAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveAdd;
    private javax.swing.JButton btnSaveTax;
    private javax.swing.JPanel center;
    private javax.swing.JCheckBox chkHasTax;
    private javax.swing.JCheckBox chkTax;
    private javax.swing.JCheckBox chkTaxAdd;
    private javax.swing.JPanel display;
    private javax.swing.JPanel edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCreatedBy;
    private javax.swing.JLabel lblDateCreated;
    private javax.swing.JTextArea lblDescription;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRate;
    private javax.swing.JList lstFees;
    private javax.swing.JPanel panelFeeInfo;
    private javax.swing.JPanel pnlFinanceSetting;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextArea txtDescriptionAdd;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameAdd;
    private ca.robokids.robooffice.desktop.customSwing.CurrencyJTextField txtRate;
    private ca.robokids.robooffice.desktop.customSwing.CurrencyJTextField txtRateAdd;
    private ca.robokids.robooffice.desktop.customSwing.CurrencyJTextField txtTax;
    // End of variables declaration//GEN-END:variables

   @Override
   public void initialize() {
      refresh();
   }

   @Override
   public void refresh() {
      chkTaxAdd.setSelected(true);
   
      feeModel.clear();
      
      List<Fee> fees;
      try {
         fees = FinanceSetting.loadAllFees();
         for (Fee f: fees)
      {
         feeModel.addElement(f);
      }
      } catch (DatabaseException ex) {
         PopupMessage.createErrorPopUp(ex.getMessage(), null);
      }
      ;
      try {
         txtTax.setText(String.valueOf(FinanceSetting.getTax()));
      } catch (DatabaseException ex) {
         PopupMessage.createErrorPopUp(ex.getMessage(), null);
      }
      
      if (feeModel.size() > 0)
      {
         lstFees.setSelectedIndex(0);
      }else
      {
         btnEdit.setEnabled(false);
         btnDelete.setEnabled(false);
      }
      
      
   }

   @Override
   public void setFocus() {
      this.txtTax.requestFocus();
   }
   
   private void switchCard(String card) {
      CardLayout c = (CardLayout) panelFeeInfo.getLayout();
      c.show(panelFeeInfo, card);
      if ("add".equals(card))
      {
         this.txtDescriptionAdd.setText("");
         this.txtNameAdd.setText("");
         this.txtRateAdd.setText("");
         chkTaxAdd.setSelected(true);
      }
   }

   private void populateFields() {
      this.lblCreatedBy.setText(fee.getCreated_by().toString());
      this.lblDateCreated.setText(fee.getDate_created().toString());
      this.lblDescription.setText(fee.getDescription());
      this.lblName.setText(fee.getName());
      this.lblRate.setText(fee.getRateString());
      
      this.txtDescription.setText(fee.getDescription());
      this.txtName.setText(fee.getName());
      this.txtRate.setText(String.valueOf(fee.getRate()));

      chkHasTax.setSelected(fee.isTax());
      chkTax.setSelected(fee.isTax());
   }

   private void setFee(Fee fee) {
      this.fee = fee;
      populateFields();
   }
   private void errorMsg(String message) {
      lblMsg.setForeground(new Color(255,102,102));
      lblMsg.setText(message);
   }
   private void Msg(String message)
   {
      lblMsg.setForeground(new Color(0,204,51));
      lblMsg.setText(message);
   }

   private Fee getEditFields() {
      Fee fee = new Fee();
      fee.setName(txtName.getText().trim());
      fee.setDescription(txtDescription.getText().trim());
      fee.setRate(Float.valueOf(txtRate.getText()));
      fee.setTax(chkTax.isSelected());
      return fee;
   }
   
   private Fee getAddFields(){
      Fee fee = new Fee();
      fee.setName(txtNameAdd.getText().trim());
      fee.setDescription(txtDescriptionAdd.getText().trim());
      fee.setRate(Float.valueOf(txtRateAdd.getText()));
      fee.setTax(chkTaxAdd.isSelected());
      return fee;
   }
}
