/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.robokids.robooffice.desktop.tabs.students;

import ca.robokids.exception.BadFieldException;
import ca.robokids.exception.DatabaseException;
import ca.robokids.robooffice.desktop.loaders.FontsLoader;
import ca.robokids.robooffice.desktop.main.TabManager;
import ca.robokids.robooffice.desktop.tabs.Tab;
import ca.robokids.robooffice.desktop.util.PopupMessage;
import ca.robokids.robooffice.entity.student.Sex;
import ca.robokids.robooffice.entity.student.Student;
import ca.robokids.robooffice.entity.user.PasswordQuestion;
import ca.robokids.robooffice.logic.student.StudentManager;
import ca.robokids.robooffice.logic.usermanagement.UserActivity;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Coldsoft
 */
public class NewStudentTab extends javax.swing.JPanel implements Tab {

   /**
    * Creates new form NewStudentTab
    */
   public NewStudentTab() {
      initComponents();
      initialize();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        centre = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        rdoBoy = new javax.swing.JRadioButton();
        rdoGirl = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        calBirthday = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboCity = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtZipcode = new ca.robokids.robooffice.desktop.customSwing.PostalCodeJTextField();
        txtAddress = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        phoneMother = new ca.robokids.robooffice.desktop.customSwing.PhoneNumberPanel();
        phoneFather = new ca.robokids.robooffice.desktop.customSwing.PhoneNumberPanel();
        phoneHome = new ca.robokids.robooffice.desktop.customSwing.PhoneNumberPanel();
        phoneEmergency = new ca.robokids.robooffice.desktop.customSwing.PhoneNumberPanel();
        txtMother = new javax.swing.JTextField();
        txtFather = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSchool = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSavePay = new javax.swing.JButton();
        btnSaveOnly = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        rdoNewspaper = new javax.swing.JRadioButton();
        rdoWebsite = new javax.swing.JRadioButton();
        rdoFriends = new javax.swing.JRadioButton();
        rdoOther = new javax.swing.JRadioButton();
        txtOther = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        lblMsg = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, FontsLoader.getTitleBorderFont()));

        jLabel1.setFont(FontsLoader.getStaticLabelFont());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("First Name*");

        txtFirstname.setFont(FontsLoader.getTextFieldFont());

        buttonGroup1.add(rdoBoy);
        rdoBoy.setFont(FontsLoader.getStaticLabelFont());
        rdoBoy.setSelected(true);
        rdoBoy.setText("Boy");

        buttonGroup1.add(rdoGirl);
        rdoGirl.setFont(FontsLoader.getStaticLabelFont());
        rdoGirl.setText("Girl");

        jLabel2.setFont(FontsLoader.getStaticLabelFont());
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Last Name*");

        txtLastname.setFont(FontsLoader.getTextFieldFont());

        jLabel3.setFont(FontsLoader.getStaticLabelFont());
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Birthday*");

        calBirthday.setFont(FontsLoader.getTextFieldFont());
        calBirthday.setMaxSelectableDate(new java.util.Date(253370797289000L));
        calBirthday.setMinSelectableDate(new java.util.Date(-62135737111000L));

        jLabel4.setFont(FontsLoader.getStaticLabelFont());
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fields with  *  must be filled ");

        jLabel5.setFont(FontsLoader.getStaticLabelFont());
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Address*");

        jLabel6.setFont(FontsLoader.getStaticLabelFont());
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("City*");

        cboCity.setEditable(true);
        cboCity.setFont(FontsLoader.getComboBoxFont());
        cboCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Richmond", "Vancouver", "West Vancouver", "North Vancouver", "Burnaby", "Coquitlam", "Port Coquitlam", "Delta", "Surrey", "Port Moody", "Langley", " " }));

        jLabel7.setFont(FontsLoader.getStaticLabelFont());
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Postal Code");

        txtZipcode.setFont(FontsLoader.getTextFieldFont());

        txtAddress.setFont(FontsLoader.getTextFieldFont());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(FontsLoader.getStaticLabelFont());
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Mother's name*:");

        jLabel9.setFont(FontsLoader.getStaticLabelFont());
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Mother's phone*");

        jLabel10.setFont(FontsLoader.getStaticLabelFont());
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Father's name");

        jLabel11.setFont(FontsLoader.getStaticLabelFont());
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Father's phone");

        jLabel12.setFont(FontsLoader.getStaticLabelFont());
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Home phone");

        jLabel13.setFont(FontsLoader.getStaticLabelFont());
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Emergency number*");

        phoneMother.setFont(FontsLoader.getTextFieldFont());

        phoneFather.setFont(FontsLoader.getTextFieldFont());

        phoneHome.setFont(FontsLoader.getTextFieldFont());

        phoneEmergency.setFont(FontsLoader.getTextFieldFont());

        txtMother.setFont(FontsLoader.getTextFieldFont());

        txtFather.setFont(FontsLoader.getTextFieldFont());

        jLabel14.setFont(FontsLoader.getStaticLabelFont());
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Email*");

        txtEmail.setFont(FontsLoader.getTextFieldFont());

        jLabel17.setFont(FontsLoader.getStaticLabelFont());
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("School*");

        txtSchool.setFont(FontsLoader.getTextFieldFont());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress)
                            .addComponent(cboCity, 0, 163, Short.MAX_VALUE)
                            .addComponent(txtFirstname)
                            .addComponent(txtLastname)
                            .addComponent(txtSchool)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(rdoBoy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoGirl)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(phoneEmergency, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phoneHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phoneFather, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtFather, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMother, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(phoneMother, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(370, 370, 370))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoBoy)
                            .addComponent(rdoGirl))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtMother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneMother, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtFather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneFather, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneEmergency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnCancel.setFont(FontsLoader.getButtonFont());
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSavePay.setFont(FontsLoader.getButtonFont());
        btnSavePay.setText("Save + Pay");
        btnSavePay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePayActionPerformed(evt);
            }
        });

        btnSaveOnly.setFont(FontsLoader.getButtonFont());
        btnSaveOnly.setText("Save (pay later)");
        btnSaveOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveOnlyActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Office Use", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, FontsLoader.getTitleBorderFont()));

        jLabel15.setFont(FontsLoader.getStaticLabelFont());
        jLabel15.setText("Hear Robokids from*:");

        buttonGroup2.add(rdoNewspaper);
        rdoNewspaper.setFont(FontsLoader.getStaticLabelFont());
        rdoNewspaper.setSelected(true);
        rdoNewspaper.setText("Newspaper");

        buttonGroup2.add(rdoWebsite);
        rdoWebsite.setFont(FontsLoader.getStaticLabelFont());
        rdoWebsite.setText("Website");

        buttonGroup2.add(rdoFriends);
        rdoFriends.setFont(FontsLoader.getStaticLabelFont());
        rdoFriends.setText("Friends");

        buttonGroup2.add(rdoOther);
        rdoOther.setFont(FontsLoader.getStaticLabelFont());
        rdoOther.setText("Other:");
        rdoOther.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdoOtherStateChanged(evt);
            }
        });

        txtOther.setFont(FontsLoader.getDynamicLabelFont());
        txtOther.setEnabled(false);

        jLabel16.setFont(FontsLoader.getStaticLabelFont());
        jLabel16.setText("Notes:");

        txtNotes.setColumns(20);
        txtNotes.setFont(FontsLoader.getTextFieldFont());
        txtNotes.setLineWrap(true);
        txtNotes.setRows(5);
        jScrollPane1.setViewportView(txtNotes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdoNewspaper)
                            .addComponent(rdoWebsite)
                            .addComponent(rdoFriends))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdoOther)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOther))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoNewspaper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoWebsite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoFriends)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoOther)
                    .addComponent(txtOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
        );

        lblMsg.setFont(FontsLoader.getErrorLabelFont());
        lblMsg.setForeground(new java.awt.Color(255, 0, 0));
        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout centreLayout = new javax.swing.GroupLayout(centre);
        centre.setLayout(centreLayout);
        centreLayout.setHorizontalGroup(
            centreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centreLayout.createSequentialGroup()
                        .addComponent(btnSavePay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveOnly)
                        .addGap(55, 55, 55)
                        .addComponent(btnCancel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        centreLayout.setVerticalGroup(
            centreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(centreLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(centreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSavePay)
                            .addComponent(btnSaveOnly)
                            .addComponent(btnCancel))
                        .addGap(12, 12, 12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(centre, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

   private void btnSavePayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePayActionPerformed

      if (save())
      {
         TabManager.closeTab(this.getName());
         //OPEN PAYMENT TAB;
      }

      
      
   }//GEN-LAST:event_btnSavePayActionPerformed

   private void btnSaveOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveOnlyActionPerformed

         if (save()){
            TabManager.closeTab(this.getName());
         }

   }//GEN-LAST:event_btnSaveOnlyActionPerformed

   private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      TabManager.closeTab(this.getName());
   }//GEN-LAST:event_btnCancelActionPerformed

   private void rdoOtherStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdoOtherStateChanged
      if (rdoOther.isSelected())
      {
         txtOther.setEnabled(true);
      }else
      {
         txtOther.setText("");
         txtOther.setEnabled(false);
      }
   }//GEN-LAST:event_rdoOtherStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSaveOnly;
    private javax.swing.JButton btnSavePay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser calBirthday;
    private javax.swing.JComboBox cboCity;
    private javax.swing.JPanel centre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMsg;
    private ca.robokids.robooffice.desktop.customSwing.PhoneNumberPanel phoneEmergency;
    private ca.robokids.robooffice.desktop.customSwing.PhoneNumberPanel phoneFather;
    private ca.robokids.robooffice.desktop.customSwing.PhoneNumberPanel phoneHome;
    private ca.robokids.robooffice.desktop.customSwing.PhoneNumberPanel phoneMother;
    private javax.swing.JRadioButton rdoBoy;
    private javax.swing.JRadioButton rdoFriends;
    private javax.swing.JRadioButton rdoGirl;
    private javax.swing.JRadioButton rdoNewspaper;
    private javax.swing.JRadioButton rdoOther;
    private javax.swing.JRadioButton rdoWebsite;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFather;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtMother;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtOther;
    private javax.swing.JTextField txtSchool;
    private ca.robokids.robooffice.desktop.customSwing.PostalCodeJTextField txtZipcode;
    // End of variables declaration//GEN-END:variables

   @Override
   public void initialize() {
      refresh();
   }

   @Override
   public void refresh() {
      this.lblMsg.setText("");
      this.txtFirstname.setText("");
      this.txtLastname.setText("");
      this.txtEmail.setText("");
      this.txtMother.setText("");
      this.txtFather.setText("");
      this.phoneEmergency.reset();
      this.phoneFather.reset();
      this.phoneMother.reset();
      this.phoneHome.reset();
      this.txtZipcode.setText("");
      this.txtNotes.setText("");
      this.txtOther.setText("");
      this.txtSchool.setText("");
      this.rdoBoy.setSelected(true);
      this.rdoNewspaper.setSelected(true);
      
      
   }

   @Override
   public void setFocus() {
      this.txtFirstname.requestFocus();
   }

   private boolean save() {
      try {
         Student s;

            s = getStudentFields();
         
         s.setActive(true);
         s.setDeleted(false);
         s.setCreateDate(new java.sql.Date(new Date().getTime()));
         s.setCreated_by(UserActivity.loginUser);
         s.setJoinDate(s.getCreateDate());
         s.setPassword("robokids");
         s.setUserName("robokids");
         s.setPasswordAnswer("robokids");
         PasswordQuestion p = new PasswordQuestion();
         p.setPassword_qestion_id(1);
         s.setPasswordQuestion(p);
         s.setProspective(true);
         
         StudentManager.addStudent(s);
         return true;
      } catch (BadFieldException ex) {
          lblMsg.setText(ex.getMessage());
          return false;
      }catch (DatabaseException ex) {
          PopupMessage.createErrorPopUp(ex.getMessage(), null);
          return false;
      }
      
   }

   private Student getStudentFields() throws BadFieldException {
      Student s = new Student();
      s.setFirstName(txtFirstname.getText().trim());
      s.setLastName(txtLastname.getText().trim());
      if (rdoBoy.isSelected())
      {
         s.setSex(Sex.BOY);
         
      }else
      {
         s.setSex(Sex.GIRL);
      }
      Date date = calBirthday.getDate();
      if (date == null)
         throw new BadFieldException("Birthday is incorrectly filled.");
      
      java.sql.Date birthday = new java.sql.Date(date.getTime());
      s.setBirthday(birthday);
      s.setAddress(txtAddress.getText().trim());
      String city = (String)cboCity.getSelectedItem();
      s.setCity(city);
      s.setZipcode(txtZipcode.getText().trim());
      s.setSchool(txtSchool.getText().trim());
      //Contacts
      s.setMother(txtMother.getText().trim());
      s.setFather(txtFather.getText().trim());
      
      String txtPhone = this.phoneMother.getPhone();
      if (txtPhone == null && !this.phoneMother.isEmpty())
         throw new BadFieldException("Mother's phone number format incorrect");
      s.setMotherPhone(txtPhone);
        
      txtPhone = this.phoneFather.getPhone();
      if (txtPhone == null && !this.phoneFather.isEmpty())
         throw new BadFieldException("Father's phone number format incorrect");
      s.setFatherPhone(txtPhone);
      
      txtPhone = this.phoneHome.getPhone();
      if (txtPhone == null && !this.phoneHome.isEmpty())
         throw new BadFieldException("Home phone number format incorrect");
      s.setHomePhone(txtPhone);
      
      txtPhone = this.phoneEmergency.getPhone();
      if (txtPhone == null && !this.phoneEmergency.isEmpty())
         throw new BadFieldException("Emergency phone number format incorrect");
      s.setEmergency(txtPhone);
      
      s.setEmail(txtEmail.getText().trim());
      
      s.setHearFrom(getHearFrom());
      
      s.setNotes(txtNotes.getText().trim());
      
      return s;
   }

   private String getHearFrom() {
      if (rdoNewspaper.isSelected())
         return "Newspaper";
      if (rdoWebsite.isSelected())
         return "Website";
      if (rdoFriends.isSelected())
         return "Friends";
      if (rdoOther.isSelected())
      {
         if (txtOther.getText().trim().length() < 1)
            return "Other";
         return txtOther.getText().trim();
      }
      return "Other";
   }
   
}
