/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.robokids.robooffice.desktop.tabs.students;

import ca.robokids.robooffice.desktop.tabs.components.FilterListModel;
import ca.robokids.robooffice.desktop.loaders.FontsLoader;
import ca.robokids.robooffice.desktop.tabs.Tab;
import ca.robokids.robooffice.entity.student.Student;
import ca.robokids.robooffice.logic.student.StudentManager;
import de.javasoft.swing.JYSearchField;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.Action;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Coldsoft
 */
public class ViewAllStudentsTab extends javax.swing.JPanel implements Tab, Action {

   /**
    * Creates new form ViewAllStudentsTab
    */
   List<Student> students;
   FilterListModel<Student> activeStudentsModel = new FilterListModel();
   FilterListModel<Student> inactiveStudentsModel = new FilterListModel();
   FilterListModel<Student> prospectiveStudentsModel = new FilterListModel();
   DefaultComboBoxModel<StudentType> typesModel = new DefaultComboBoxModel();
   JYSearchField txtSearch = new JYSearchField();

   public ViewAllStudentsTab() {
      initComponents();
      initialize();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstStudents = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        cboType = new javax.swing.JComboBox();
        btnRefresh = new javax.swing.JButton();
        pnlSearch = new javax.swing.JPanel();

        lstStudents.setFont(FontsLoader.getListFont());
        lstStudents.setModel(activeStudentsModel);
        jScrollPane1.setViewportView(lstStudents);

        jLabel1.setFont(FontsLoader.getStaticLabelFont());
        jLabel1.setText("Students");

        cboType.setFont(FontsLoader.getComboBoxFont());
        cboType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Inactive", "Prospective" }));
        cboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTypeActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/robokids/robooffice/desktop/images/refreshIcon.png"))); // NOI18N
        btnRefresh.setMaximumSize(new java.awt.Dimension(35, 35));
        btnRefresh.setMinimumSize(new java.awt.Dimension(35, 35));
        btnRefresh.setPreferredSize(new java.awt.Dimension(35, 35));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
        );

        pnlSearch.setLayout(new javax.swing.BoxLayout(pnlSearch, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 691, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

   private void cboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTypeActionPerformed
      
      lstStudents.setModel(getVisibleModel());
      lstStudents.repaint();
      filterList(txtSearch.getText().trim());
      this.txtSearch.requestFocus();
   }//GEN-LAST:event_cboTypeActionPerformed

   private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
      refresh();
   }//GEN-LAST:event_btnRefreshActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox cboType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstStudents;
    private javax.swing.JPanel pnlSearch;
    // End of variables declaration//GEN-END:variables

   @Override
   public void initialize() {

      initSearchTextfields();
      StudentType[] types = StudentType.values();

      for (int i = 0; i < types.length; i++) {
         typesModel.addElement(types[i]);
      }
      cboType.setModel(typesModel);

      txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {

         public void focusGained(java.awt.event.FocusEvent evt) {
            txtSearch.setSelectionStart(0);
            txtSearch.setSelectionEnd(txtSearch.getText().length());
         }
      });
      refresh();
   }

   @Override
   public void refresh() {
      //Testing Search
      activeStudentsModel.clear();
      inactiveStudentsModel.clear();
      prospectiveStudentsModel.clear();
      List<Student> list = StudentManager.getSampleStudentList();
      for (Student s : list) {
         activeStudentsModel.addElement(s);
      }
      list = StudentManager.getSampleStudentList();
      for (Student s : list) {
         inactiveStudentsModel.addElement(s);
      }
      list = StudentManager.getSampleStudentList();
      for (Student s : list) {
         prospectiveStudentsModel.addElement(s);
      }
   }

   @Override
   public void setFocus() {
      this.txtSearch.requestFocus();
   }

   @Override
   public void actionPerformed(ActionEvent e) {
      filterList(txtSearch.getText().trim());
   }

   @Override
   public Object getValue(String key) {
      return null;
   }

   @Override
   public void putValue(String key, Object value) {
   }

   private FilterListModel getVisibleModel()
   {
      switch (typesModel.getElementAt(cboType.getSelectedIndex())) {
         case ACTIVE:
            return activeStudentsModel;
         case INACTIVE:
            return inactiveStudentsModel;
         case PROSPECTIVE:
            return prospectiveStudentsModel;
            
         default:
            System.err.println("Error in getVisibleModel Switch in ViewAllStudentsTab");
            return activeStudentsModel;
      }
            
   }
   private void filterList(String text) {
      System.out.println("in filterList: " + text + " word");
      this.getVisibleModel().filter(text);
      lstStudents.repaint();
   }

   private void initSearchTextfields() {
      txtSearch.setPromptText("Enter student name");
      txtSearch.setSearchControlsPosition(JYSearchField.SearchControlsPosition.SEARCH_LEADING_CLEAR_TRAILING);
      txtSearch.setSearchMode(JYSearchField.SearchMode.AUTO);
      txtSearch.setSearchAction(this);
      txtSearch.setSearchDelay(200);
      txtSearch.setPreferredSize(new Dimension(200, 25));
      txtSearch.setFont(FontsLoader.getTextFieldFont());
      this.pnlSearch.add(txtSearch);
   }

   public enum StudentType {

      ACTIVE("Active"),
      INACTIVE("Inactive"),
      PROSPECTIVE("Prospective");
      String display;

      private StudentType(String value) {
         display = value;
      }

      public String toString() {
         return display;
      }
   }
}
