/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.robokids.robooffice.gui.test;

import ca.robokids.robooffice.desktop.tabs.students.components.AttendancePanel;
import ca.robokids.robooffice.desktop.tabs.students.components.ClassroomPanel;
import ca.robokids.robooffice.entity.schoolmetadata.Classroom;
import ca.robokids.robooffice.entity.schoolmetadata.Course;
import ca.robokids.robooffice.entity.schoolmetadata.CourseSection;
import ca.robokids.robooffice.entity.student.CourseProgress;
import ca.robokids.robooffice.entity.student.Progress;
import ca.robokids.robooffice.entity.student.Student;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Coldsoft
 */
public class AttendanceDriver extends javax.swing.JFrame {

   ClassroomPanel cp;
   ClassroomPanel cp2;
   AttendancePanel attendancePanel;
      

   /**
    * Creates new form AttendanceDriver
    */
   public AttendanceDriver() {
      initComponents();
      attendancePanel = new AttendancePanel();
      attendancePanel.addClassroom(getClassroom(), getProgresses(), true);
      attendancePanel.addClassroom(getClassroom(), getProgresses(), false);
      attendancePanel.addClassroom(getClassroom(), getProgresses(), false);
      attendancePanel.addClassroom(getClassroom(), getProgresses(), false);
      attendancePanel.addClassroom(getClassroom(), getProgresses(), false);
      attendance.add(attendancePanel);


   }

   private Classroom getClassroom() {
      Classroom r = new Classroom();
      r.setName("LegoKids Classroom");
      r.setCapacity(10);
      return r;

   }

   private List<Progress> getProgresses() {
      List<Progress> list = new ArrayList();
      for (int i = 0; i < 21; i++) {
         CourseProgress cp = new CourseProgress();
         Student s = new Student();
         s.setFirstName("Marco");
         s.setLastName("Luo");

         Course course = new Course();
         course.setCode("LK1A");
         CourseSection cs = new CourseSection();
         cs.setCourse(course);

         cp.setStudent(s);
         cp.setSection(cs);


         list.add(cp);
      }
      return list;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attendance = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(400, 400));

        attendance.setLayout(new javax.swing.BoxLayout(attendance, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attendance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(attendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      try {
         javax.swing.UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel");

         //</editor-fold>

         /*
          * Create and display the form
          */
         java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               new AttendanceDriver().setVisible(true);
            }
         });
      } // Variables declaration - do not modify
      // End of variables declaration
      catch (ClassNotFoundException ex) {
         Logger.getLogger(AttendanceDriver.class.getName()).log(Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         Logger.getLogger(AttendanceDriver.class.getName()).log(Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         Logger.getLogger(AttendanceDriver.class.getName()).log(Level.SEVERE, null, ex);
      } catch (UnsupportedLookAndFeelException ex) {
         Logger.getLogger(AttendanceDriver.class.getName()).log(Level.SEVERE, null, ex);
      }
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attendance;
    // End of variables declaration//GEN-END:variables
}
