/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package ca.robokids.robooffice.gui.test;

import ca.robokids.robooffice.desktop.customSwing.TimeslotDialog;
import ca.robokids.robooffice.desktop.loaders.FramePropertyLoader;
import ca.robokids.robooffice.desktop.util.PopupMessage;
import ca.robokids.robooffice.entity.schoolmetadata.Timeslot;
import de.javasoft.swing.JYTabbedPane;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Coldsoft
 */
public class TestJFrame extends javax.swing.JFrame {

    /** Creates new form TestJFrame */
    public TestJFrame() {
        initComponents();
        tabPane.setCloseButtonStrategy(JYTabbedPane.CloseButtonStrategy.ALL_TABS);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        txtTabname = new javax.swing.JTextField();
        lblMsg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tabPane = new de.javasoft.swing.JYTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdd.setText("add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("remove");

        lblMsg.setFont(new Font("宋体", Font.PLAIN, 12));
        lblMsg.setText(FramePropertyLoader.getLoadingMessage());

        jButton1.setText("Timeslots");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btnAdd)
                .addGap(70, 70, 70)
                .addComponent(btnRemove)
                .addGap(51, 51, 51)
                .addComponent(txtTabname, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove)
                    .addComponent(txtTabname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblMsg)
                .addGap(195, 195, 195)
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      JPanel newpanel = new JPanel();
      newpanel.setName(txtTabname.getText());
      tabPane.addTab(txtTabname.getText(), new JPanel());
      JPanel content = tabPane.getContentPanel();
      Component[] coms = content.getComponents();
      String s = null;
      for (Component c : coms)
      {
         
         s += ((JPanel)c).getName();
      }
      lblMsg.setText(s);
              System.out.println(PopupMessage.createConfirmPopUp(null, null));
   }//GEN-LAST:event_btnAddActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      TimeslotDialog time = new TimeslotDialog(this,true);
      time.setLocationRelativeTo(this);
      time.setVisible(true);
      
      Timeslot t = time.getTimeslot();
      System.out.println(t);
      if (t != null){
         lblMsg.setText(t.toString());
         System.out.println(t);
      }
      
   }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.put("Synthetica.rootPane.titlePane.title.center", Boolean.TRUE);
            UIManager.put("Synthetica.tabbedPane.tab.selected.bold", Boolean.TRUE);
            UIManager.put("Synthetica.rootPane.titlePane.dropShadow", Boolean.TRUE);
            UIManager.put("Synthetica.rootPane.titlePane.gap", 5);
            javax.swing.UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblMsg;
    private de.javasoft.swing.JYTabbedPane tabPane;
    private javax.swing.JTextField txtTabname;
    // End of variables declaration//GEN-END:variables

}
